import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFileSync,readdirSync,existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
test('actual public build includes every v2 route and first home entry without dev files',()=>{
 execFileSync(process.execPath,['scripts/build-preview.mjs'],{cwd:root});
 for(const path of ['index.html','design-system/index.html','home/index.html','my-land/index.html','barcode/index.html','og-park/index.html','my-info/index.html','page.mjs','render.mjs','navigation.mjs','tokens.css','shell.css','design-system/foundations.mjs','design-system/foundations.css','design-system/color-values.mjs','components/index.html','components/render.mjs','components/preview.mjs','components/styles.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/mileage.mjs','components/mileage.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/home-controls.mjs','components/home-controls.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/list-row.mjs','components/list-row.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/section-heading.mjs','components/section-heading.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/selection.mjs','components/selection.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/input.mjs','components/input.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/dialog.mjs','components/dialog.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/notice.mjs','components/notice.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/feedback.mjs','components/feedback.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/loading.mjs','components/loading.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/snackbar.mjs','components/snackbar.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/help.mjs','components/help.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/icon-button.mjs','components/icon-button.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/tabs.mjs','components/tabs.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/chips.mjs','components/chips.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/badges.mjs','components/badges.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['components/media.mjs','components/media.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const name of ['surfaces','quantity','sheet','date-time','attachments'])for(const extension of ['mjs','css'])assert.ok(existsSync(join(root,'dist/v2/components',name+'.'+extension)),name+' is published');
 assert.ok(existsSync(join(root,'dist/v2/components/overlay.mjs')),'overlay controller is published');
 for(const path of ['components/catalog.mjs','components/explorer.mjs','components/explorer.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['subnavigation.mjs','review-navigation.mjs'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 assert.ok(existsSync(join(root,'dist/screens/my-info-3d-test/home-controls.mjs')),'shared home controls are published');
 for(const path of ['barcode/render.mjs','barcode/preview.mjs','barcode/screen.css','components/screen.css','components/screen-stage.css','components/screen-preview.mjs'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/render.mjs','home/preview.mjs','home/screen.css','home/search.mjs','home/search.css','home/styles.css','home/category.mjs','home/category.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/nearby.mjs','home/nearby.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/store.mjs','home/store.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/main-menu.mjs','home/main-menu.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/full-menu.mjs','home/full-menu.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/menu-detail.mjs','home/menu-detail.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/store-reservation.mjs','home/store-reservation.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/store-waiting.mjs','home/store-waiting.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/store-news.mjs','home/store-news.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/store-event.mjs','home/store-event.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/news-list.mjs','home/news-list.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/news-detail.mjs','home/news-detail.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/event-list.mjs','home/event-list.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/event-detail.mjs','home/event-detail.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['home/reviews.mjs','home/reviews.css','home/information.mjs','home/information.css','home/remaining-gallery.mjs'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['my-info/render.mjs','my-info/preview.mjs','my-info/styles.css','my-info/screen.css','components/bottom-navigation.css'])assert.ok(existsSync(join(root,'dist/v2',path)),path+' is published');
 for(const path of ['my-info/navigation-comparisons.mjs','my-info/navigation-comparisons.css'])assert.equal(existsSync(join(root,'dist/v2',path)),false,path+' is retired');
 const home=readFileSync(join(root,'dist/index.html'),'utf8');
 const entries=[...home.matchAll(/<a class="artifact-link"[^>]*href="([^"]+)"[^>]*>[\s\S]*?<strong>([^<]+)<\/strong>/g)].map(x=>[x[1],x[2]]);
 assert.deepEqual(entries.slice(0,2),[['v2/','3D컨셉 디자인 v2'],['design-system/canvas/','디자인 캔버스 열기']]);
 function walk(path){return readdirSync(path,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?walk(join(path,entry.name)):[join(path,entry.name)]);}
 const files=walk(join(root,'dist'));
 assert.ok(files.every(path=>!path.includes('.test.')&&!path.endsWith('.md')&&!path.split('/').some(name=>name.startsWith('.'))),'public build excludes tests, Markdown, dotfiles and credentials');
});
