import {bottomSheet,surface,mileage,button,textButton,sectionHeading} from '../../components/index.mjs';
import {homeScreen} from '../home/render.mjs';
// Code128 specimen for OG0000000000000000, not a real member identifier.
const specimen='<svg class="og-barcode-bars" viewBox="0 0 176 72" preserveAspectRatio="none" role="img" aria-label="실제 회원 정보가 아닌 샘플 바코드"><rect x="10" width="2" height="72"/><rect x="13" width="1" height="72"/><rect x="16" width="1" height="72"/><rect x="21" width="1" height="72"/><rect x="25" width="3" height="72"/><rect x="29" width="2" height="72"/><rect x="32" width="2" height="72"/><rect x="35" width="1" height="72"/><rect x="39" width="1" height="72"/><rect x="43" width="1" height="72"/><rect x="45" width="3" height="72"/><rect x="49" width="4" height="72"/><rect x="54" width="2" height="72"/><rect x="57" width="2" height="72"/><rect x="61" width="2" height="72"/><rect x="65" width="2" height="72"/><rect x="68" width="2" height="72"/><rect x="72" width="2" height="72"/><rect x="76" width="2" height="72"/><rect x="79" width="2" height="72"/><rect x="83" width="2" height="72"/><rect x="87" width="2" height="72"/><rect x="90" width="2" height="72"/><rect x="94" width="2" height="72"/><rect x="98" width="2" height="72"/><rect x="101" width="2" height="72"/><rect x="105" width="2" height="72"/><rect x="109" width="2" height="72"/><rect x="112" width="2" height="72"/><rect x="116" width="2" height="72"/><rect x="120" width="2" height="72"/><rect x="123" width="2" height="72"/><rect x="127" width="2" height="72"/><rect x="131" width="2" height="72"/><rect x="134" width="2" height="72"/><rect x="138" width="2" height="72"/><rect x="142" width="2" height="72"/><rect x="147" width="1" height="72"/><rect x="150" width="1" height="72"/><rect x="153" width="2" height="72"/><rect x="158" width="3" height="72"/><rect x="162" width="1" height="72"/><rect x="164" width="2" height="72"/></svg>';
export function barcodeScreen({total=12400,available=10000,loggedIn=true}={}){
 const balance=loggedIn?surface({className:'og-barcode-balance',contentHTML:mileage({total,available,max:Math.max(total+5000,5000),density:'payment'})}):'';
 const code=loggedIn?specimen+'<div class="og-barcode-number"><strong>OG 0000 0000 0000 0000</strong></div>':'<div class="og-barcode-guest"><div aria-hidden="true" class="og-barcode-obscured">'+specimen+'</div><p>로그인 또는 회원 가입 후에 적립 가능합니다.</p>'+button({label:'로그인 또는 가입하러 가기'})+'</div>';
 const card=surface({className:'og-barcode-card',contentHTML:sectionHeading({title:'내 바코드'})+code+(loggedIn?'<div class="og-barcode-actions">'+button({label:'영수증 적립',variant:'secondary'})+button({label:'마일리지 사용'})+'</div>':'')});
 const body='<div class="og-barcode-content">'+balance+card+textButton({label:'마일리지 적립/사용 안내',className:'og-barcode-guide'})+'</div>';
 return '<section class="og-barcode-screen" inert aria-label="바코드 화면"><div class="og-barcode-backdrop" aria-hidden="true">'+homeScreen()+'</div><div class="og-barcode-scrim"></div>'+bottomSheet({title:'',headerAttributes:{'aria-label':'바코드'},bodyHTML:body,actions:[]})+'</section>';
}
export function barcodeBoard(){
 return [
 ['기본 · 보유 12,400 M / 사용 가능 10,000 M',{}],
 ['5,000 M 미만 · 보유 2,400 M',{total:2400,available:0}],
 ['보유 마일리지가 없을 때',{total:0,available:0}],
 ['로그인하지 않았을 때',{loggedIn:false}]
 ].map(([title,props],i)=>'<section class="og-barcode-example"><h3 class="history-state-label">'+title+'</h3><div class="screen-page-content"><div class="screen-artboard">'+barcodeScreen(props)+'</div>'+(i===0?'<div class="screen-design-notes"><h3>사용 가능 금액부터</h3><p>보유 잔액과 실제 사용 가능 금액을 분리하고, 사용 가능 금액을 크게 표시했습니다.</p><h3>다음 사용 단위까지</h3><p>12,400 M 예시는 다음 15,000 M까지 2,600 M가 필요합니다. 구간 진행률은 48%입니다.</p><h3>기존 동선 유지</h3><p>영수증 적립·마일리지 사용·안내를 유지합니다. 바코드는 실제 회원 정보가 아닌 샘플입니다.</p></div>':'')+'</div></section>').join('');
}
