import {iconButton} from '../../components/button/render.mjs';
import {thumbnail} from '../../components/avatar/render.mjs';
import {tabs} from '../../components/tabs-chips/render.mjs';
import {escapeHTML as e,icon} from '../../components/core.mjs';
export function storeNavigation({menu=false,reserve=false,wait=false,news=false,event=false}={}){return ['홈',...(menu?['메뉴']:[]),...(reserve||wait?[reserve&&wait?'예약/웨이팅':reserve?'예약':'웨이팅']:[]),...(news||event?[news&&event?'소식/이벤트':news?'소식':'이벤트']:[]),'리뷰','매장 상세정보','위치찾기'];}
export function storeScreen({name='회원점명',category='카페/베이커리',address='서울특별시 성동구 도로명 주소',status='영업 중',subStatus='',images=[],logo='',promotion='회원점 소개 제목',description='회원점에서 등록한 소개 내용입니다.',bookmarked=false,contentHTML=null,selectedSection=0,...availability}={}){
 return '<div class="og-store" inert><header class="og-store-toolbar">'+iconButton({name:'arrow_back_ios_new',label:'뒤로가기'})+'<div>'+iconButton({name:'location_on',label:'길찾기'})+iconButton({name:'share',label:'공유'})+iconButton({name:bookmarked?'favorite':'favorite_border',label:'찜',className:bookmarked?'og-store-bookmarked':''})+'</div></header><section class="og-store-identity">'+(logo?'<img class="og-store-logo" src="'+e(logo)+'" alt="" width="34" height="34">':'')+'<div class="og-store-identity-copy"><div class="og-store-name"><h2>'+e(name)+'</h2><span>'+e(category)+'</span></div><p>'+e(address)+'</p>'+(status?'<p class="og-store-status"><strong>'+e(status)+'</strong><span>'+e(subStatus)+'</span></p>':'')+'</div>'+(availability.event?'<span class="og-store-event">'+icon('star')+'<span>EVENT</span></span>':'')+'</section>'+tabs({label:'매장 내용 이동',items:storeNavigation(availability),selected:selectedSection,className:'og-store-tabs'})+'<div class="og-store-body">'+(contentHTML??('<div class="og-store-photo">'+thumbnail({src:images[0]||'https://og-familystore-image.s3.ap-northeast-2.amazonaws.com/ogapp/no_image.png',alt:name+' 매장 사진'})+(images.length?'<span class="og-store-count">1 · '+images.length+'</span>':'')+'</div><section class="og-store-promotion">'+(promotion?'<h3>'+e(promotion)+'</h3>':'')+'<p>'+e(description)+'</p></section>'))+'</div></div>';
}
export function storeBoard({imageSrc='',store={}}={}){return [
 ['기본 첫 화면',{images:store.images||[imageSrc,imageSrc],logo:store.logo??imageSrc,menu:true,reserve:true,wait:true,news:true,event:true},'매장명·주소·영업 상태를 먼저 보여주고, 그 아래에 사진을 배치했습니다.'],
 ['메뉴·예약·웨이팅·소식이 없는 매장',{images:store.images?.slice(0,1)||[imageSrc],menu:false,reserve:false,wait:false,news:false,event:false},'제공하지 않는 항목은 탐색 메뉴에서 제외합니다.'],
 ['사진이 없는 매장',{images:[],reserve:true},'기존 대체 이미지를 사용하며 사진 수 표시는 생략합니다.']
 ].map(([title,props,copy])=>'<section class="og-home-example"><h3>'+title+'</h3><div class="screen-page-content"><div class="screen-artboard">'+storeScreen({...store,...props})+'</div><div class="screen-design-notes"><p>'+copy+'</p></div></div></section>').join('');}
export const storePrompt='매장 상세 첫 화면을 첨부 캡처와 CSS로 구현하세요. 기존 lib/0_pages/01_home/shop_panel.dart, shop_panel_items/shop_contents.dart, StoreImageView를 유지하고 스타일만 적용합니다. 이번 캔버스는 근처보기 방문하기→ShopPanel 독립 화면 진입의 상단 모습입니다. 지도핀에서 열리는 패널 진입은 별도 기존 panelController 분기를 유지합니다. 뒤로가기·길찾기·공유·찜과 기존 로그인/미리보기 제한을 유지합니다. 로고는 있을 때만, 매장명·업종·주소·영업 label/sublabel과 hasEvent의 EVENT를 표시합니다. 운영상태를 임의 문자열로 재계산하지 말고 기존 RuntimeValidater 결과를 사용합니다. 임시/정기휴무 본문 차단은 기존 코드대로 유지하며 이번 기본 영업상태 시안이 이를 제거하라는 뜻이 아닙니다. 탐색은 별도페이지 탭이 아니라 본문 섹션 스크롤 이동입니다. 홈·조건부 메뉴·예약/웨이팅/예약/웨이팅 없음·소식/이벤트/소식/이벤트 없음·리뷰·매장 상세정보·위치찾기 순서와 기존 조건을 유지합니다. 사진은 화면너비-32높이, StoreImageView 스와이프와 사진상세 진입을 유지합니다. 사진없음은 기존 noImageUrl이며 이 분기에는 카운터가 없습니다. 사진뒤 promotionTitle/promotionContents는 기존값을 표시하고 본문2줄/펼침 동작을 유지합니다. 이번 시안은 첫화면만이며 하단 주요메뉴·예약·웨이팅·소식·리뷰·상세정보·위치 섹션을 삭제하라는 뜻이 아닙니다. 조이바 칩전환/상위3개 강조는 미적용으로 별도 검토합니다. 예시사진·주소·상태는 배치용입니다. 공통 iconButton/tabs/thumbnail 및 OG토큰을 재사용하세요. 실제이동/찜/공유/탭스크롤은 캔버스에 구현하지 않습니다. 렌더러 design-system/pages/home/store.mjs, CSS store.css.';
