import {escapeHTML as e} from '../../design-system/components/core.mjs';
import {surface,menuTile} from '../../design-system/components/surfaces/render.mjs';
import {icon,mileageCoin} from './icons.mjs';
const number=value=>new Intl.NumberFormat('ko-KR').format(value);
const menus=[['이용내역','receipt'],['공지·알림','bell'],['멤버십','membership'],['문의하기','support'],['설정','settings'],['내 정보','account']];
const exampleVisits=[{name:'스시샤워 반주헌',date:'09.24 목',reviewed:false},{name:'준오헤어 용산아이파크몰',date:'09.11 금',reviewed:true},{name:'직화생소금구이 종로익선점',date:'05.30 토',reviewed:true}];
export function renderMyInfoTest({available=15000,total=16000,shared=1250,visits=exampleVisits}={}){
 const min=total>=10000?10000:0,max=20000;
 const position=value=>Math.max(0,Math.min(100,(value-min)/(max-min)*100));
 const balance=surface({className:'mileage-card',attributes:{'aria-label':'OG 마일리지'},contentHTML:
  '<div class="mileage-top">'+mileageCoin()+'<div class="mileage-title"><div><span>사용 가능한 OG 마일리지</span><button class="mileage-info" data-preview="마일리지 안내" aria-label="마일리지 안내">'+icon('info',{size:16})+'</button></div><strong>'+number(available)+' M</strong></div><button class="mileage-history" data-preview="마일리지 내역">내역보기 '+icon('chevron',{size:16})+'</button></div>'+
  '<div class="mileage-graph" role="meter" aria-label="총 보유 마일리지" aria-valuemin="'+min+'" aria-valuemax="'+max+'" aria-valuenow="'+Math.max(min,Math.min(total,max))+'" aria-valuetext="'+number(total)+' M"><span class="graph-held" style="--progress:'+position(total)+'%"></span><span class="graph-available" style="--progress:'+position(available)+'%"></span><span class="graph-marker" style="--progress:'+position(available)+'%"></span></div><div class="graph-labels" aria-hidden="true"><span>'+number(min)+'M</span><span>'+number((min+max)/2)+'M</span><span>'+number(max)+'M</span></div>'+
  '<dl class="mileage-breakdown"><div><dt>총 보유 마일리지</dt><dd>'+number(total)+' M</dd></div><div><dt>공유 적립</dt><dd><span>공유인 3</span> '+number(shared)+' M</dd></div></dl>'});
 const recent=surface({className:'recent-card',contentHTML:'<div class="recent-heading"><h2>최근 방문</h2><button class="icon-button" data-preview="최근 방문 전체보기" aria-label="최근 방문 전체보기">'+icon('chevron',{size:20})+'</button></div><ul class="visit-list">'+visits.map(v=>'<li><span class="visit-symbol">'+icon('utensils',{size:24})+'</span><div class="visit-copy"><strong>'+e(v.name)+'</strong><span>'+e(v.date)+'</span></div><button class="review-button'+(!v.reviewed?' review-write':'')+'" data-preview="'+(v.reviewed?'내 리뷰':'후기 작성')+'" aria-label="'+e(v.name)+' '+(v.reviewed?'내 리뷰':'후기 작성')+'">'+(v.reviewed?'내 리뷰':icon('pencil',{size:18}))+'</button></li>').join('')+'</ul>'});
 const navigation=[['홈','home'],['마이랜드','compass'],['바코드','scan'],['오지파크','star'],['내 정보','user']];
 return '<section class="my-info-test"><header class="profile-header"><div class="header-actions"><button class="icon-button" data-preview="알림" aria-label="알림">'+icon('bell',{size:20})+'</button><button class="icon-button" data-preview="설정" aria-label="설정">'+icon('settings',{size:20})+'</button></div><div class="profile-row"><span class="profile-placeholder" role="img" aria-label="프로필 캐릭터 미적용">'+icon('user',{size:28})+'</span><div><h1>맑은 땅콩 님</h1><button class="profile-edit" data-preview="프로필 수정">수정하기 '+icon('chevron',{size:16})+'</button></div></div></header><div class="page-content">'+balance+recent+'<nav class="service-menu" aria-label="내 정보 메뉴">'+menus.map(([label,name])=>menuTile({label,className:'service-tile',attributes:{'data-preview':label},iconHTML:'<span class="service-face"><img src="./media/'+name+'.png" width="80" height="80" alt="" decoding="async"></span>'})).join('')+'</nav></div><nav class="bottom-navigation" aria-label="주 메뉴">'+navigation.map(([label,name])=>'<button class="nav-item'+(name==='scan'?' nav-barcode':'')+(name==='user'?' is-selected':'')+'" data-preview="'+label+'"'+(name==='user'?' aria-current="page"':'')+'><span class="nav-face">'+icon(name,{size:name==='scan'?28:26,dimensional:name!=='scan'})+'</span><span>'+label+'</span></button>').join('')+'</nav></section>';
}
