import {escapeHTML as e} from '../../design-system/components/core.mjs';
import {surface,menuTile} from '../../design-system/components/surfaces/render.mjs';
import {icon} from './icons.mjs';
const number=value=>new Intl.NumberFormat('ko-KR').format(value);
const menus=[['이용내역','receipt'],['공지·알림','bell'],['멤버십','membership'],['문의하기','support'],['설정','settings'],['내 정보','account']];
// Crop positions exported by Figma from the shared, unmodified 384×256 menu sheet.
const menuRegions={receipt:['-2.16%','-7.31%'],bell:['-93.39%','-7.31%'],membership:['-196.02%','-8.56%'],support:['-3.71%','-96.78%'],settings:['-100.34%','-96.47%'],account:['-196.54%','-96.99%']};
const menuArt=name=>'<span class="service-face"><span class="service-art" data-art="'+name+'" style="--art-left:'+menuRegions[name][0]+';--art-top:'+menuRegions[name][1]+'"><img src="./media/figma/menu-icons.png" width="384" height="256" alt="" decoding="async"></span></span>';
const figmaIcon=(name,width,height=width)=>'<img src="./media/figma/'+name+'.svg" width="'+width+'" height="'+height+'" alt="" decoding="async">';
const exampleVisits=[{name:'스시산원 반주헌',date:'09.24 목',reviewed:false},{name:'준오헤어 용산아이파크몰',date:'09.11 금',reviewed:true},{name:'석암생소금구이 종로익선점',date:'05.30 토',reviewed:true}];
export function renderMyInfoTest({available=15000,total=16000,shared=1250,visits=exampleVisits}={}){
 const min=total>=10000?10000:0,max=20000;
 const position=value=>Math.max(0,Math.min(100,(value-min)/(max-min)*100));
 const balance=surface({className:'mileage-card',attributes:{'aria-label':'OG 마일리지'},contentHTML:
  '<div class="mileage-top"><img class="m-coin" src="./media/figma/mileage-m.png" width="48" height="48" alt="" decoding="async"><div class="mileage-title"><div><span>사용 가능한 OG 마일리지</span><button class="mileage-info" data-preview="마일리지 안내" aria-label="마일리지 안내">'+figmaIcon('mileage-info',10)+'</button></div><strong>'+number(available)+' M</strong></div><button class="mileage-history" data-preview="마일리지 내역">내역보기 '+figmaIcon('mileage-chevron',14)+'</button></div>'+
  '<div class="mileage-graph" role="meter" aria-label="총 보유 마일리지" aria-valuemin="'+min+'" aria-valuemax="'+max+'" aria-valuenow="'+Math.max(min,Math.min(total,max))+'" aria-valuetext="'+number(total)+' M"><span class="graph-held" style="--progress:'+position(total)+'%;--cap:'+(total>min?3:0)+'px"></span><span class="graph-available" style="--progress:'+position(available)+'%;--cap:'+(available>min?9:0)+'px;--fill-min:'+(available>min?20:0)+'px"></span><span class="graph-marker" style="--progress:'+position(available)+'%"'+(available<=min?' hidden':'')+'>'+figmaIcon('mileage-marker',20)+'</span></div><div class="graph-labels" aria-hidden="true"><span>'+number(min)+'M</span><span>'+number((min+max)/2)+'M</span><span>'+number(max)+'M</span></div>'+
  '<div class="mileage-breakdown"><span class="mileage-divider" aria-hidden="true">'+figmaIcon('mileage-divider',310,1)+'</span><dl class="mileage-rows"><div><dt>총 보유 마일리지</dt><dd>'+number(total)+' M</dd></div><div><dt>공유 적립</dt><dd><span>공유인 3</span> |'+number(shared)+' M</dd></div></dl></div>'});
 const recent=surface({className:'recent-card',contentHTML:'<div class="recent-heading"><h2>최근 방문</h2><button class="icon-button" data-preview="최근 방문 전체보기" aria-label="최근 방문 전체보기">'+figmaIcon('recent-chevron',20)+'</button></div><ul class="visit-list">'+visits.map(v=>'<li><span class="visit-symbol"><img src="./media/figma/recent-utensils.svg" width="32" height="32" alt="" decoding="async"></span><div class="visit-copy"><strong>'+e(v.name)+'</strong><span>'+e(v.date)+'</span></div><button class="review-button'+(!v.reviewed?' review-write':'')+'" data-preview="'+(v.reviewed?'내 리뷰':'후기 작성')+'" aria-label="'+e(v.name)+' '+(v.reviewed?'내 리뷰':'후기 작성')+'">'+(v.reviewed?'내 리뷰':'<img src="./media/figma/review-pencil.svg" width="16" height="16" alt="" decoding="async">')+'</button></li>').join('')+'</ul>'});
 const navigation=[['홈','home'],['마이랜드','compass'],['바코드','scan'],['오지파크','star'],['내 정보','user']];
 return '<section class="my-info-test"><header class="profile-header"><div class="header-actions"><button class="icon-button" data-preview="알림" aria-label="알림">'+figmaIcon('header-bell',20)+'</button><button class="icon-button" data-preview="설정" aria-label="설정">'+figmaIcon('header-settings',20)+'</button></div><div class="profile-row"><span class="profile-avatar" role="img" aria-label="프로필 캐릭터"><span class="avatar-layer avatar-base"><img src="./media/figma/profile-base.png" width="1536" height="1024" alt="" decoding="async"></span><span class="avatar-layer avatar-overlay"><img src="./media/figma/profile-overlay.png" width="324" height="573" alt="" decoding="async"></span></span><div><h1>맑은 땅콩 님</h1><button class="profile-edit" data-preview="프로필 수정">수정하기 '+figmaIcon('profile-chevron',14)+'</button></div></div></header><div class="page-content">'+balance+recent+'<nav class="service-menu" aria-label="내 정보 메뉴">'+menus.map(([label,name])=>menuTile({label,className:'service-tile',attributes:{'data-preview':label},iconHTML:menuArt(name)})).join('')+'</nav></div><nav class="bottom-navigation" aria-label="주 메뉴">'+navigation.map(([label,name])=>'<button class="nav-item'+(name==='scan'?' nav-barcode':'')+(name==='user'?' is-selected':'')+'" data-preview="'+label+'"'+(name==='user'?' aria-current="page"':'')+'><span class="nav-face">'+icon(name,{size:name==='scan'?28:26,dimensional:name!=='scan'})+'</span><span>'+label+'</span></button>').join('')+'</nav></section>';
}
