import {bottomSheet,surface,sectionHeading,listRow,iconButton,textField,button,dialog,avatar} from '../../components/index.mjs';
import {escapeHTML as e,icon} from '../../components/core.mjs';
import {myInfo} from './render.mjs';
const maskedName=name=>{const n=name.trim();return n.length<2?n:n.length===2?n[0]+'*':n[0]+'*'.repeat(n.length-2)+n.at(-1);};
const maskedPhone=phone=>{if(phone.length<7)return phone;const p=phone.split('-');return p.length>=3?p[0]+'-****-'+p[2]:phone.length===11?phone.slice(0,3)+'-****-'+phone.slice(7):phone;};
const status=(label,checked)=>'<span class="og-account-status'+(checked?' is-checked':'')+'">'+icon(checked?'check_box':'check_box_outline_blank')+'<span>'+label+'</span></span>';
export function account({name='홍길동',phone='010-1234-5678',joined='2024-05-20',mileage=16000,visible=false,authenticated=false,confirmation='',assetsOpen=false,nickname='맑은 땅콩',birthday='',gender='미입력',inviter={name:'윤지환',date:'2026-05-28'},view='all'}={}){
 const confirmed=confirmation==='회원탈퇴';
 const info='<div class="og-account-heading">'+sectionHeading({title:'가입 정보'})+iconButton({label:visible?'개인정보 숨기기':'개인정보 표시',name:visible?'visibility':'visibility_off'})+'</div>'+[['이름',visible?name:maskedName(name)],['전화번호',visible?phone:maskedPhone(phone)],['가입일',joined.slice(0,10)],['보유 마일리지',Number(mileage).toLocaleString('ko-KR')+' M']].map(([title,value])=>listRow({title,value,interactive:false})).join('');
 const profile=surface({className:'og-account-profile',contentHTML:sectionHeading({title:'프로필 정보'})+textField({label:'닉네임',value:nickname,attributes:{readonly:true}})+textField({label:'생일',value:birthday,placeholder:'미입력',attributes:{readonly:true},trailingHTML:iconButton({label:'생일 입력하기',name:'calendar_today'})})+listRow({title:'성별',value:gender,interactive:false})});
 const referral=surface({className:'og-account-referral',contentHTML:sectionHeading({title:'나를 초대한 공유인'})+(inviter?'<div class="og-account-inviter">'+avatar({size:'medium',label:'공유인 프로필'})+'<div><strong>'+e(maskedName(inviter.name))+'</strong><p>'+e(inviter.date)+' 초대</p></div></div>':'<p class="og-account-no-inviter">등록된 공유인이 없습니다.</p>')});
 const withdrawal=sectionHeading({title:'회원 탈퇴'})+'<div class="og-account-auth">'+status('본인 인증',authenticated)+button({label:'인증하기',variant:'secondary',size:'small'})+'</div>'+textField({labelHTML:status('탈퇴 확인',confirmed),value:confirmation,placeholder:'회원탈퇴',hint:'확인을 위해 "회원탈퇴"라고 입력해주세요',attributes:{readonly:true}})+button({label:'오지고랜드 회원 탈퇴하기',variant:'secondary',className:'og-account-withdraw'+(confirmed?' is-confirmed':'')});
 const overlay=assetsOpen?'<div class="og-account-overlay">'+dialog({title:'자산 소멸 확인',body:'마일리지 등 남은 자산이 있습니다. 회원 탈퇴시 모든 자산은 소멸됩니다.\n\n회원 탈퇴를 진행하시겠습니까?',actions:[{label:'취소',variant:'secondary'},{label:'확인'}]})+'</div>':'';
 return '<section class="og-history-screen og-account" inert aria-label="내 회원 정보"><div class="og-history-backdrop" aria-hidden="true">'+myInfo()+'</div><div class="og-history-scrim"></div>'+bottomSheet({title:'내 회원 정보',action:view==='withdrawal'||assetsOpen?'닫기':'저장하기',bodyHTML:'<div class="og-account-groups" data-authenticated="'+authenticated+'" data-confirmed="'+confirmed+'">'+(view==='withdrawal'||assetsOpen?surface({className:'og-account-withdrawal',contentHTML:withdrawal}):(view==='profile'?'':surface({className:'og-account-info',contentHTML:info}))+profile+referral+listRow({title:'회원 탈퇴',className:'og-account-withdraw-link'}))+'</div>'})+overlay+'</section>';
}
export function accountBoard(){
 const states=[['기본 · 개인정보 숨김',{}],['개인정보를 표시했을 때',{visible:true}],['프로필·초대 정보 · 아래 영역',{view:'profile',birthday:'1995-04-12',gender:'여'}],['초대한 공유인이 없을 때',{view:'profile',inviter:null}],['회원 탈퇴 · 기존 인증 절차',{view:'withdrawal'}],['본인 인증과 탈퇴 확인을 마쳤을 때',{view:'withdrawal',authenticated:true,confirmation:'회원탈퇴'}],['남은 자산이 있을 때 · 확인창',{authenticated:true,confirmation:'회원탈퇴',assetsOpen:true}]];
 return states.map(([label,props],i)=>'<section class="'+(i?'history-empty-example':'')+'"><h3 class="history-state-label">'+label+'</h3><div class="screen-page-content"><div class="screen-artboard">'+account(props)+'</div>'+(i===0?'<div class="screen-design-notes"><h3>가입 정보와 회원 탈퇴</h3><p>기획 17페이지를 기준으로 가입 정보·프로필·초대한 공유인을 구분했습니다. 기존 카드의 얕은 그림자와 테두리를 재사용합니다. 저장하기는 시트 하단에 고정합니다.</p><h3>인증과 확인</h3><p>이름·전화번호와 공유인 이름은 가립니다. 공유인 카드의 이름·날짜와 생일·성별은 배치 예시입니다. 성별은 기획처럼 조회값으로 표시하며 변경 정책은 검토 대상입니다. 탈퇴 예시는 기존 인증 절차를 별도로 보여줍니다.</p></div>':'')+'</div></section>').join('');
}
