// Ordering is the canvas reading order. Reserved screens contain no implemented UI.
export const myInfoPages=[
 ['main','내 정보','메인',''],
 ['mileage','마일리지 내역','바텀시트','내 정보 → 마일리지'],
 ['history','이용내역','바텀시트','내 정보 → 이용 내역'],
 ['reservation-detail','예약 상세','세부 화면','이용내역 → 예약'],
 ['reservation-change','예약 변경','바텀시트','예약 상세 → 변경'],
 ['waiting-detail','웨이팅 상세','세부 화면','이용내역 → 웨이팅'],
 ['order-detail','Q오더 상세','세부 화면','이용내역 → Q오더'],
 ['review-history','리뷰 내역','세부 화면','내 정보 → 최근 방문 → 내 리뷰'],
 ['notices','공지·내 알림','바텀시트','내 정보 → 공지·알림'],
 ['notice-detail','공지 상세','세부 화면','공지·내 알림 → 공지'],
 ['membership','멤버십','바텀시트','내 정보 → 멤버십'],
 ['support','문의하기','바텀시트','내 정보 → 문의하기'],
 ['faq','자주 묻는 질문','세부 화면','문의하기 → FAQ'],
 ['opinion','의견 보내기','세부 화면','문의하기 → 의견 보내기'],
 ['customer-center','고객센터','세부 화면','문의하기 → 고객센터'],
 ['policies','약관·정책','세부 화면','고객센터 → 약관·정책'],
 ['policy-detail','약관·정책 상세','세부 화면','약관·정책 → 문서'],
 ['settings','설정','바텀시트','내 정보 → 설정'],
 ['password','비밀번호 변경','세부 화면','설정 → 보안 설정'],
 ['account','가입 정보','바텀시트','내 정보 → 내 정보'],
 ['photo-review','포토 리뷰','세부 화면','매장 → 리뷰 작성 → 내역 선택'],
 ['review-write','사진 리뷰 등록','세부 화면','포토 리뷰 → 포토 리뷰 작성'],
 ['services','서비스','바텀시트','내 정보 → 서비스'],
 ['character','프로필 캐릭터 선택','보류','내 정보 → 프로필'],
].map(([key,title,kind,route],index)=>({id:'my-info-'+key,title,kind,route,number:'MY-'+String(index+1).padStart(2,'0'),ready:['main','mileage','history','reservation-detail','reservation-change','waiting-detail','order-detail','review-history','notices','notice-detail','membership','support','faq','opinion','customer-center','policies','policy-detail','settings','password','account','photo-review','review-write','services'].includes(key)}));
