import {bottomSheet,surface,iconButton,textButton,textField,avatar,button} from '../../components/index.mjs';
import {escapeHTML as e,icon} from '../../components/core.mjs';
import {myInfo} from './render.mjs';
export function membership({code='OG1234',referral='',count=3,shareOpen=false,memberNumber='OG-00012345',nickname='맑은 땅콩',joined='2026-05-28',view='all'}={}){
 const identity='<div class="og-membership-identity">'+avatar({size:'large',label:'멤버십 프로필'})+'<div><span>멤버십 인증서</span><h3>'+e(nickname)+'</h3></div></div><dl class="og-membership-details"><div><dt>회원번호</dt><dd>'+e(memberNumber)+'</dd></div><div><dt>가입일</dt><dd>'+e(joined)+'</dd></div></dl>';
 const own=code?identity+'<div class="og-membership-code"><h3>내 공유 코드</h3><div><strong>'+e(code)+'</strong>'+iconButton({label:'내 공유 코드 복사',name:'content_copy'})+'</div></div><div class="og-membership-qr" role="img" aria-label="공유 QR코드 디자인 예시">'+icon('qr_code_2')+'</div><div class="og-membership-share"><span>초대 링크</span>'+iconButton({label:'공유 링크 복사',name:'content_copy'})+'</div><div class="og-membership-count"><span>내가 초대한 공유인 수</span><strong>'+Number(count).toLocaleString('ko-KR')+' 명</strong></div>':'<h3>내 공유 코드</h3><p class="og-membership-no-code">1번 이상 적립을 하면 내 공유 코드가 생깁니다.</p>';
 const body='<div class="og-membership-content">'+(view==='registration'?'':surface({className:'og-membership-own',contentHTML:own}))+(code&&view!=='registration'?'<div class="og-membership-export">'+button({label:'이미지 저장',variant:'secondary'})+button({label:'친구에게 공유'})+'</div>':'')+surface({className:'og-membership-referral',contentHTML:textField({label:referral?'나를 초대한 공유인의 공유코드':'나를 초대한 공유인 등록',value:referral,attributes:{disabled:!!referral},trailingHTML:!referral?iconButton({label:'공유인 코드 입력',name:'edit'}):''})})+'</div>';
 const share=shareOpen&&code?'<div class="og-membership-overlay">'+bottomSheet({title:'친구에게 오지고랜드 공유하기',bodyHTML:'<div class="og-membership-channels">'+textButton({label:'카카오톡 공유'})+textButton({label:'링크 공유'})+'</div>',actions:[]})+'</div>':'';
 return '<section class="og-history-screen og-membership" inert aria-label="멤버십"><div class="og-history-backdrop" aria-hidden="true">'+myInfo()+'</div><div class="og-history-scrim"></div>'+bottomSheet({title:'멤버십',bodyHTML:body,action:'저장하기'})+share+'</section>';
}
export function membershipBoard(){
 const states=[['기본 상태',{}],['공유인을 등록한 상태 · 아래 등록 영역',{referral:'AB5678',view:'registration'}],['내 공유 코드가 없을 때',{code:'',count:0}],['공유하기 · 열린 상태',{shareOpen:true}]];
 return states.map(([title,props],i)=>'<section class="'+(i?'history-empty-example':'')+'"><h3 class="history-state-label">'+title+'</h3><div class="screen-page-content"><div class="screen-artboard">'+membership(props)+'</div>'+(i===0?'<div class="screen-design-notes"><h3>멤버십 인증서</h3><p>기획 17페이지의 회원번호·닉네임·가입일·초대 수·공유코드와 QR을 한 카드로 묶었습니다. 이미지 저장과 친구에게 공유는 카드 바로 아래에 배치합니다.</p><h3>등록 영역 구분</h3><p>나를 초대한 공유인의 코드는 아래 카드에 분리했습니다. 같은 밝은 블루와 부드러운 그림자를 사용했습니다. 코드·회원정보는 배치 예시이며 QR은 스캔되지 않는 디자인 표식입니다. 이미지 저장·공유도 정적 시안입니다.</p></div>':'')+'</div></section>').join('');
}
