import {attachments,imageViewer} from '../components/attachments/render.mjs';
import {storeImage} from './specimen-media.mjs';
{
 const board=document.createElement('section');board.id='attachments';board.className='board';
 const src=storeImage();
 const states=[['empty','첨부 전'],['ready','첨부 후'],['uploading','업로드 중'],['error','업로드 실패'],['removed','삭제 후']];
 const viewer=(mode,label)=>'<figure class="attachment-example"><figcaption>'+label+'</figcaption>'+imageViewer({src,alt:'매장 이미지',mode}).replace('class="og-image-viewer"','class="og-image-viewer" data-media-example inert')+'</figure>';
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / IMAGE & ATTACHMENT</span><h1>이미지 보기·첨부</h1><p>첨부 상태는 썸네일 옆에서, 큰 이미지는 별도 화면에서 확인합니다.</p></div><section id="attachment-picker-specimen" class="attachment-section"><div class="attachment-heading"><h2>사진 첨부</h2><button data-field-prompt="attachment-picker-specimen">AI 프롬프트</button></div><div class="attachment-examples">'+states.map(([state,label,body])=>'<figure class="attachment-example" data-attachment-state="'+state+'"><figcaption>'+label+'</figcaption>'+attachments({src,alt:'첨부한 매장 이미지',state}).replace('class="og-attachment-box"','class="og-attachment-box" data-media-example inert')+'</figure>').join('')+'</div><p class="attachment-note">썸네일 96 × 96 · 모서리 12 · 항목 사이 간격 12. 삭제 아이콘은 오른쪽 위에 표시합니다. 실패해도 이미지를 남겨 재시도하거나 삭제할 수 있게 합니다.</p></section><section id="image-viewer-specimen" class="attachment-section"><div class="attachment-heading"><h2>이미지 보기</h2><button data-field-prompt="image-viewer-specimen">AI 프롬프트</button></div><div class="attachment-examples">'+viewer('fit','전체 보기')+viewer('zoom','확대 상태')+viewer('error','불러오기 실패')+'</div><p class="attachment-note">전체 보기에서는 이미지 비율을 유지하고 잘리지 않게 표시합니다. 확대 상태에서는 주변부가 화면 밖으로 이어지며, 닫기와 이미지 순서는 같은 위치에 둡니다.</p></section><h2>표현 기준</h2><ul class="rules-list"><li>추가 버튼은 점선 테두리, 첨부한 이미지는 실선 테두리로 구분합니다.</li><li>업로드 중과 실패 상태는 문구를 함께 표시합니다. 오류를 색만으로 전달하지 않습니다.</li><li>미리보기는 정사각형으로 맞추되, 큰 이미지 보기에서는 원래 비율을 유지합니다.</li><li>삭제 아이콘과 닫기는 최소 48 영역을 확보합니다. 확대 이미지 위에서도 닫기 버튼이 가려지지 않게 합니다.</li></ul>';
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='attachments';nav.textContent='이미지 보기·첨부';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('이미지 보기·첨부','attachments'));
}
