import {avatar,thumbnail as renderThumbnail} from '../components/avatar/render.mjs';
import {specimenAttributes} from './specimen-utils.mjs';
import {storeImage} from './specimen-media.mjs';
/* Avatar and image presentation, reusing the existing profile face icon. */
{
 const board=document.createElement('section');board.id='avatar';board.className='board';
 const face=size=>avatar({size});
 // Resolve the same design tokens for the embedded image, not an independent palette.
 const thumbnail=(extra='')=>renderThumbnail({src:storeImage(),alt:'매장 아이콘',attributes:specimenAttributes(extra)});
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / AVATAR & THUMBNAIL</span><h1>프로필 이미지·썸네일</h1><p>사람은 원형으로, 매장과 콘텐츠는 둥근 사각형으로 구분합니다.</p></div>'+
 '<section id="avatar-specimen" class="avatar-section"><div class="avatar-heading"><h2>프로필 이미지</h2><button data-field-prompt="avatar-specimen">AI 프롬프트</button></div><div class="avatar-sizes">'+[['small','32 · 작은 목록'],['medium','48 · 기본 목록'],['large','64 · 프로필']].map(([size,label])=>'<figure>'+face(size)+'<figcaption>'+label+'</figcaption></figure>').join('')+'</div><div class="avatar-context">'+face('large')+'<div><strong>맑은 땅콩 님</strong><p>프로필 캐릭터 선택</p></div></div><p class="avatar-note">얼굴은 중앙에 배치하고 비율을 유지합니다. 밝은 테두리와 부드러운 그림자로 배경과 구분합니다. 이미지가 없거나 불러오지 못하면 기본 프로필을 표시합니다.</p><ul class="rules-list"><li>이름과 이미지 사이 간격은 16px입니다.</li><li>프로필을 누를 수 있는 경우 터치 영역을 최소 48px로 확보합니다.</li><li>로딩 중에도 원형 영역의 크기는 유지합니다.</li></ul></section>'+
 '<section id="thumbnail-specimen" class="avatar-section"><div class="avatar-heading"><h2>썸네일</h2><button data-field-prompt="thumbnail-specimen">AI 프롬프트</button></div><div class="avatar-context">'+thumbnail()+'<div><strong>회원점명</strong><p>정사각형 64 × 64 · 목록에 사용</p></div></div><div class="media-pair"><figure>'+thumbnail('data-ratio="wide"')+'<figcaption>영역 채우기 · 16:9<br>가운데를 기준으로 가장자리를 잘라 맞춥니다.</figcaption></figure><figure>'+thumbnail('data-ratio="wide" data-fit="contain"')+'<figcaption>전체 보이기 · 16:9<br>로고·상품이 잘리면 안 되는 경우에 사용합니다.</figcaption></figure></div><p class="avatar-note">모서리 12px · 테두리 1px. 이미지는 늘려서 찌그러뜨리지 않고, 남는 공간은 밝은 배경색으로 채웁니다.</p><h3>이미지 상태</h3><label class="media-controls" for="media-state">표시 상태<select id="media-state"><option value="ready">정상</option><option value="loading">불러오는 중</option><option value="empty">이미지 없음</option><option value="error">불러오기 실패</option></select></label>'+thumbnail('id="media-live" data-ratio="wide"')+'<p id="media-status" class="avatar-note" role="status">이미지를 표시합니다.</p><ul class="rules-list"><li>이미지 상태가 바뀌어도 크기와 비율은 유지합니다.</li><li>불러오는 동안은 같은 크기의 회색 영역을 표시합니다.</li><li>이미지가 없거나 불러오지 못하면 기본 아이콘과 안내 문구를 표시합니다.</li><li>썸네일 자체에는 버튼 그림자나 선택 효과를 넣지 않습니다.</li></ul></section>';
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='avatar';nav.textContent='프로필·썸네일';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('프로필·썸네일','avatar'));
}
