import {badge as renderBadge,countBadge,unreadDot} from '../components/badges/render.mjs';
/* Static state labels and local count preview. No notification or service state is changed. */
{
 const board=document.createElement('section');board.id='badges';board.className='board';board.dataset.component='badges';
 const badge=(label,tone='neutral',size='small')=>renderBadge({label,tone,size});
 const roles=[
  ['NEW','brand','새로운 항목','신규 콘텐츠를 짧게 강조합니다.','--app-action / --app-selected'],
  ['진행 중','info','진행 상태','이벤트·신청 등의 현재 상태를 표시합니다. 로딩 스피너 대신 쓰지 않습니다.','--app-info / --app-info-surface'],
  ['✓ 완료','success','처리 완료','완료가 확인된 항목에만 사용합니다. 단순 선택 상태와 구분합니다.','--app-success / --app-success-surface'],
  ['! 확인 필요','warning','추가 확인','추가 행동이 필요한 상태입니다. 이유와 다음 행동은 본문에서 안내합니다.','--app-warning / --app-warning-surface'],
  ['종료','neutral','종료·일반 상태','끝난 항목이나 중립적인 구분입니다. 종료됐다는 이유만으로 목록을 비활성화하지 않습니다.','--app-text-secondary / --app-disabled-surface'],
  ['! 실패','error','처리 실패','문제 발생을 표시합니다. 상세 원인과 재시도는 별도의 설명·버튼으로 제공합니다.','--app-error / --app-error-surface']
 ];
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / BADGE & STATUS</span><h1>배지·상태 표시</h1><p>상태를 짧게 표시하고, 제목보다 작게 배치합니다.</p></div>'+
 '<section id="status-badge-specimen" class="badge-section"><div class="badge-section-heading"><h2>텍스트 배지</h2><button data-field-prompt="status-badge-specimen">AI 프롬프트</button></div><div id="badge-roles">'+roles.map(([text,tone,title,copy,tokens])=>'<div class="badge-role-row">'+badge(text,tone)+'<div><h3>'+title+'</h3><p>'+copy+'</p><code>'+tokens+'</code></div></div>').join('')+'</div><h3 style="margin-top:var(--app-space-6)">크기</h3><div class="badge-size-example">'+badge('진행 중','info')+'<span class="badge-note">Small · 최소 24 / 글자 12</span>'+badge('진행 중','info','medium')+'<span class="badge-note">Medium · 최소 28 / 글자 13</span></div><p class="badge-note">좌우 여백 8 · 상하 여백 2 · 모서리 4. 높이는 최소값이며 글자 확대 시 함께 늘어납니다. 버튼·필터 칩과 혼동되지 않도록 그림자·선택 효과·포인터 커서를 사용하지 않습니다.</p><h3>배치 예시</h3><div class="badge-example-box"><div class="badge-context-row"><span>공지 제목 예시</span>'+badge('NEW','brand')+'</div><div class="badge-context-row"><span>이벤트 제목 예시</span>'+badge('진행 중','info')+'</div><div class="badge-context-row"><span>지난 이벤트 제목 예시</span>'+badge('종료')+'</div></div><p class="badge-note">제목은 남은 폭에서 줄바꿈하고, 배지는 축소하거나 두 줄로 나누지 않습니다. 여러 배지가 필요한 경우 묶음 전체를 다음 줄로 배치합니다. 긴 설명은 배지에 넣지 않습니다.</p></section>'+
 '<section id="notification-badge-specimen" class="badge-section"><div class="badge-section-heading"><h2>읽지 않음 · 숫자 배지</h2><button data-field-prompt="notification-badge-specimen">AI 프롬프트</button></div><div class="badge-example-box"><label class="badge-count-controls" for="badge-count-select">예시 알림 개수 <select id="badge-count-select">'+[0,1,9,99,100,128].map(n=>'<option value="'+n+'"'+(n===9?' selected':'')+'>'+n+'개</option>').join('')+'</select></label><div class="badge-context-row"><span>알림 · 개수 표시</span>'+countBadge({id:'badge-live-count',count:9})+'</div><div class="badge-context-row"><span>공지 · 읽지 않음 여부만 표시</span>'+unreadDot({id:'badge-live-dot'})+'</div><p id="badge-count-status" class="badge-note" role="status">9개 · 숫자 배지와 읽지 않음 점을 표시합니다.</p></div><p class="badge-note">숫자: 최소 24 × 24 · 좌우 8 · 알약형 · 글자 12 / 굵기 700. 읽지 않음 점: 8 × 8. 0개는 배지와 점을 숨기고, 100개 이상은 99+로 축약합니다. 스크린리더에는 축약하지 않은 실제 개수를 전달합니다.</p><p class="badge-note">같은 항목에 점과 숫자를 중복 표시하지 않습니다. 위 두 행은 표현 방식 비교입니다. 메뉴 버튼에 올릴 경우 배지를 별도 포커스 대상으로 만들지 않고, 버튼 이름에 ‘알림, 읽지 않음 128개’처럼 통합합니다. 숫자를 모르는 로딩·조회 실패 상태를 0개로 취급하지 않습니다.</p></section>'+
 '<h2>사용 기준</h2><ul class="rules-list"><li>상태는 문구로 전달합니다. 색은 보조 신호이며 필요한 경우 체크·느낌표를 함께 사용합니다.</li><li>배지는 상태 표시이지 버튼이 아닙니다. 버튼처럼 눌리거나 선택되는 효과를 넣지 않습니다.</li><li>불러오는 중·불러오기 실패는 결과 영역에서 안내합니다. 끝난 항목의 ‘종료’와 사용 불가 상태를 혼동하지 않습니다.</li><li>숫자 변화 애니메이션이나 반복 반짝임은 넣지 않습니다.</li></ul>';
 const variants=document.createElement('section');variants.id='service-badge-specimen';variants.className='badge-section';
 variants.innerHTML='<div class="badge-section-heading"><h2>용도별 배지</h2><button data-field-prompt="service-badge-specimen">AI 프롬프트</button></div><div class="badge-example-box"><h3>공모전 진행 상태</h3><div class="og-badge-group">'+badge('진행 중','info')+badge('심사 중','warning')+badge('종료')+'</div><p class="badge-note">진행 상태는 색과 문구로 구분합니다. 심사 중은 차분한 노란색으로 표시합니다.</p><h3>매장 구분</h3><div class="og-badge-group">'+badge('회원점','brand')+badge('일반 매장')+'</div><p class="badge-note">회원점은 블루, 일반 매장은 회색으로 구분합니다.</p><h3>출품 형식</h3><div class="og-badge-group">'+['사진','영상','그림'].map(label=>badge(label)).join('')+'</div><p class="badge-note">형식은 같은 회색으로 표시해 진행 상태보다 눈에 띄지 않게 합니다.</p></div><h3>함께 배치할 때</h3><div class="badge-example-box"><div class="badge-context-row"><span>공모전 제목</span><div class="og-badge-group">'+badge('심사 중','warning')+badge('사진')+'</div></div><div class="badge-context-row"><span>매장명</span>'+badge('회원점','brand')+'</div></div>';
 board.querySelector('#notification-badge-specimen').before(variants);
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='badges';nav.textContent='배지·상태';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('배지·상태','badges'));
}
