import {surface as sharedSurface} from '../components/surfaces/render.mjs';
import {feedback,notice as renderNotice,surface} from '../components/index.mjs';
{
 const board=document.createElement('section');board.id='feedback';board.className='board';
 const empty=(symbol,title,body)=>surface({contentHTML:feedback({symbol,title,body})});
 const notice=(tone,symbol,title,body)=>renderNotice({tone,symbol,title,body});
 board.innerHTML=`<div class="board-heading"><span>COMPONENTS / FEEDBACK</span><h1>빈 화면·오류·안내</h1><p>현재 상태를 짧게 설명하고, 필요한 다음 행동을 안내합니다.</p></div>
 <section class="feedback-section" id="feedback-empty-specimen"><div class="feedback-heading"><h2>빈 화면</h2><button data-field-prompt="feedback-empty-specimen">AI 프롬프트</button></div><div class="feedback-stage">${empty('storefront','아직 방문 내역이 없어요','방문한 매장이 생기면 여기에 표시됩니다.')}${empty('search','검색 결과가 없어요','다른 매장명이나 업종으로 검색해 보세요.')}</div><ul class="rules-list"><li>내역이 없는 상태와 검색 결과가 없는 상태를 구분합니다.</li><li>빈 화면은 오류가 아닙니다. 붉은색이나 경고 아이콘을 사용하지 않습니다.</li><li>다음 행동이 명확할 때만 버튼을 넣습니다. 검색 결과가 없을 때는 검색창을 그대로 둡니다.</li></ul></section>
 <section class="feedback-section" id="feedback-error-specimen"><div class="feedback-heading"><h2>불러오기 오류</h2><button data-field-prompt="feedback-error-specimen">AI 프롬프트</button></div><div class="feedback-controls"><label for="feedback-result">재시도 결과<select id="feedback-result"><option value="success">내용 표시</option><option value="empty">내역 없음</option><option value="error">오류 유지</option></select></label><button id="feedback-reset">오류 다시 보기</button></div><div class="feedback-stage">${sharedSurface({contentHTML:`${feedback({symbol:'cloud_off',title:'불러오지 못했어요',body:'잠시 후 다시 시도해 주세요.',state:'error',action:{label:'다시 시도'},ids:{root:'feedback-live',icon:'feedback-icon',title:'feedback-title',body:'feedback-copy',action:'feedback-retry'}})}`})}</div><p id="feedback-status" role="status" class="feedback-note"></p><ul class="rules-list"><li>실패한 내용을 먼저 알리고, 사용자가 할 수 있는 행동을 한 가지 제시합니다.</li><li>원인을 알 수 없으면 네트워크나 권한 문제로 단정하지 않습니다.</li><li>다시 시도하는 동안 버튼 위치를 유지하고 중복 실행을 막습니다.</li><li>결과가 나오면 같은 영역에서 내용·빈 화면·오류로 바뀝니다.</li></ul></section>
 <section class="feedback-section" id="feedback-notice-specimen"><div class="feedback-heading"><h2>영역 내 안내</h2><button data-field-prompt="feedback-notice-specimen">AI 프롬프트</button></div><div class="feedback-stage">${notice('info','info','사진을 확인해 주세요','글자가 선명하게 보이는 사진을 선택해 주세요.')}${notice('warning','warning_amber','변경 내용이 저장되지 않았어요','화면을 나가기 전에 저장해 주세요.')}${notice('error','error_outline','저장하지 못했어요','입력한 내용은 그대로 남아 있어요. 다시 저장해 주세요.')}${notice('success','check_circle_outline','저장했어요','변경한 내용을 확인해 주세요.')}</div><p class="feedback-note">아이콘 20px · 안쪽 여백 16px · 아이콘과 문구 간격 12px · 모서리 12px.</p><ul class="rules-list"><li>안내는 관련 내용 가까이에 둡니다. 중요한 오류는 잠깐 나타났다 사라지지 않도록 합니다.</li><li>색뿐 아니라 아이콘과 문구로 상태를 구분합니다.</li><li>밝은 배경 면으로 구분하고, 그림자나 두꺼운 테두리를 더하지 않습니다.</li><li>완료가 화면에서 충분히 드러나면 별도의 완료 안내를 반복하지 않습니다.</li></ul></section>`;
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='feedback';nav.textContent='빈 화면·오류·안내';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('빈 화면·오류·안내','feedback'));
}
