import {surface as sharedSurface} from '../components/surfaces/render.mjs';
import {tooltip,popover,iconButton} from '../components/index.mjs';
{
 const board=document.createElement('section');board.id='help';board.className='board';
 board.innerHTML=`<div class="board-heading"><span>COMPONENTS / HELP</span><h1>툴팁·팝오버</h1><p>짧은 설명은 툴팁으로, 자세한 안내는 눌러서 확인합니다.</p></div>
 <section class="help-section" id="help-tooltip-specimen"><div class="help-heading"><h2>툴팁</h2><button data-field-prompt="help-tooltip-specimen">AI 프롬프트</button></div><div class="help-stage">${sharedSurface({contentHTML:`<div class="help-title-row"><strong>총 보유</strong>${iconButton({label:'총 보유 설명',info:true,className:'og-help-trigger',attributes:{id:'help-tooltip-trigger','aria-describedby':'help-tooltip'}})}</div><div class="help-preview">아이콘에 마우스를 올리거나 키보드로 이동해 보세요.</div>${tooltip({id:'help-tooltip',message:'사용 가능한 금액을 포함한 전체 마일리지입니다.'})}`})}</div><p class="help-note">본문 13px / 행간 18px · 모서리 8px · 아이콘과 간격 8px.</p><ul class="rules-list"><li>마우스를 약 0.8초 올리면 나타납니다. 키보드로 이동했을 때는 바로 표시합니다.</li><li>설명 위로 마우스를 옮겨도 유지됩니다. 다른 곳으로 이동하거나 Esc를 누르면 닫힙니다.</li><li>툴팁 안에는 버튼이나 링크를 넣지 않습니다.</li><li>반드시 알아야 할 내용은 숨기지 말고 본문에 표시합니다. 터치로 여는 상세 설명은 팝오버를 사용합니다.</li></ul></section>
 <section class="help-section" id="help-popover-specimen"><div class="help-heading"><h2>팝오버</h2><button data-field-prompt="help-popover-specimen">AI 프롬프트</button></div><div class="help-stage">${sharedSurface({contentHTML:`<div class="help-title-row"><strong>마일리지</strong>${iconButton({label:'마일리지 안내',info:true,expanded:false,className:'og-help-trigger',attributes:{id:'help-popover-trigger','aria-haspopup':'dialog','aria-controls':'help-popover'}})}</div><div class="help-preview">정보 아이콘을 누르면 마일리지 안내가 열립니다.</div>${popover({id:'help-popover',closeId:'help-popover-close',title:'마일리지 안내',body:'사용 가능 마일리지는 지금 사용할 수 있는 금액입니다. 총 보유 마일리지에는 사용 가능 금액이 포함됩니다.'})}`})}</div><p class="help-note">너비 320px · 안쪽 여백 16px · 모서리 16px · 본문 14px / 행간 22px. 터치 영역은 48px입니다.</p><ul class="rules-list"><li>아이콘을 누르면 열리고, 바깥 영역·닫기 버튼·Esc로 닫습니다.</li><li>화면 아래 공간이 부족하면 아이콘 위에 표시합니다. 좌우 가장자리에서도 안내가 잘리지 않도록 맞춥니다.</li><li>흰색 면과 부드러운 그림자로 떠 있는 느낌을 줍니다. 뒤 화면을 어둡게 가리지 않습니다.</li><li>안내가 길어지면 팝오버 대신 바텀시트나 별도 화면을 사용합니다.</li></ul></section>`;
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='help';nav.textContent='툴팁·팝오버';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('툴팁·팝오버','help'));
}
