import {publicServicesData} from '../pages/home/public-services-data.mjs?v=20260920-detail-polish';
import {publicReviewsData} from '../pages/home/public-reviews-data.mjs?v=20260920-detail-polish';
import {publicPostsData} from '../pages/home/public-posts-data.mjs?v=20260920-detail-polish';
import {publicStoreData as realStore} from '../pages/home/public-store-data.mjs?v=20260920-detail-polish';
import {activeCanvas} from './session.mjs';
import {homeBoards,canvases} from './catalog.mjs';
import {storeInfoBoard,storeInfoPrompt} from '../pages/home/store-info.mjs?v=20260920-detail-polish';
import {reviewPagesBoard,reviewPagesPrompt} from '../pages/home/review-pages.mjs?v=20260920-detail-polish';
import {storeReviewsBoard,storeReviewsPrompt} from '../pages/home/store-reviews.mjs?v=20260920-detail-polish';
import {eventPagesBoard,eventPagesPrompt} from '../pages/home/event-pages.mjs?v=20260920-detail-polish';
import {newsPagesBoard,newsPagesPrompt} from '../pages/home/news-pages.mjs?v=20260920-detail-polish';
import {updatesBoard,updatesPrompt} from '../pages/home/store-updates.mjs?v=20260920-detail-polish';
import {serviceBoard,servicePrompt} from '../pages/home/store-services.mjs?v=20260920-detail-polish';
import {menuDetailBoard,menuDetailPrompt} from '../pages/home/menu-detail.mjs?v=20260920-detail-polish';
import {fullMenuBoard,fullMenuPrompt} from '../pages/home/full-menu.mjs?v=20260920-detail-polish';
import {mainMenuBoard,mainMenuPrompt} from '../pages/home/main-menu.mjs?v=20260920-detail-polish';
import {storeBoard,storePrompt} from '../pages/home/store.mjs?v=20260920-detail-polish';
import {nearbyBoard,nearbyPrompt} from '../pages/home/nearby.mjs?v=20260920-detail-polish';
import {storeImage} from './specimen-media.mjs';
import {categoryBoard,categoryPrompt} from '../pages/home/category.mjs?v=20260920-detail-polish';
import {searchBoard,searchPrompt} from '../pages/home/search.mjs?v=20260920-detail-polish';
import {homeBoard} from '../pages/home/render.mjs?v=20260920-detail-polish';
import {focusBoard} from './canvas.js?v=20260919-partitions';
const world=document.querySelector('#world');
const title=canvases.find(c=>c.id===activeCanvas).title;
export const homeRegion=document.createElement('section');
homeRegion.id='home-region';homeRegion.className='system-region';homeRegion.setAttribute('aria-label',title);
homeRegion.innerHTML='<header class="system-area-heading"><h2>'+title+'</h2></header>';world.append(homeRegion);
const renderers=[()=>homeBoard(),()=>searchBoard(),()=>categoryBoard(),()=>nearbyBoard({imageSrc:storeImage()}),()=>storeBoard({store:realStore.store}),()=>mainMenuBoard({store:realStore.store,items:realStore.items.filter(item=>item.featured)}),()=>fullMenuBoard({store:realStore.store,items:realStore.items,imageSrc:realStore.store.images[0]}),()=>menuDetailBoard({imageSrc:storeImage(),item:realStore.items.find(item=>item.image)}),()=>serviceBoard('reservation',publicServicesData),()=>serviceBoard('waiting',publicServicesData),()=>updatesBoard('news',{imageSrc:storeImage(),publicData:publicPostsData}),()=>updatesBoard('event',{imageSrc:storeImage(),publicData:publicPostsData}),()=>newsPagesBoard('list',{imageSrc:storeImage(),publicData:publicPostsData}),()=>newsPagesBoard('detail',{imageSrc:storeImage(),publicData:publicPostsData}),()=>eventPagesBoard('list',{imageSrc:storeImage(),publicData:publicPostsData}),()=>eventPagesBoard('detail',{imageSrc:storeImage(),publicData:publicPostsData}),()=>storeReviewsBoard({imageSrc:storeImage(),publicData:publicReviewsData}),()=>reviewPagesBoard('list',{imageSrc:storeImage(),publicData:publicReviewsData}),()=>reviewPagesBoard('photo',{imageSrc:storeImage(),publicData:publicReviewsData}),()=>storeInfoBoard('info',realStore),()=>storeInfoBoard('location',realStore)];
export const homePages=homeBoards.flatMap((board,index)=>{
 if(board.canvas!==activeCanvas)return [];
 const page=document.createElement('section');page.id=board.id;page.className='screen-page';page.dataset.family='home';
 page.innerHTML='<header class="screen-page-heading"><div><span>HOME-'+String(index+1).padStart(2,'0')+' · 화면 시안</span><h2>'+board.title+'</h2></div><button type="button" data-home-prompt>AI 프롬프트</button></header>'+renderers[index]();world.append(page);return [page];
});
const sourceId=activeCanvas==='explore'?'home-main':'home-store';
const source=document.getElementById(sourceId);
// Adopt the chosen treatment through the same scoped CSS used by comparison B.
source.querySelectorAll(':scope > .og-home-example .screen-artboard').forEach(n=>n.classList.add('og-depth-subtle'));
const adoptedPrompt=source.querySelector(':scope > .screen-page-heading [data-home-prompt]');
adoptedPrompt.dataset.depthPrompt=activeCanvas==='explore'?'home':'store';
adoptedPrompt.dataset.depthSubtle='';adoptedPrompt.dataset.adoptedDepth='';
source.querySelector(':scope > .screen-page-heading span').textContent+=' · B안 적용';
const selected=homeBoards.filter(b=>b.canvas===activeCanvas);
const nav=document.createElement('nav');nav.className='screen-nav';nav.setAttribute('aria-label',title+' 페이지 이동');
nav.innerHTML=selected.map(b=>'<button type="button" data-screen-link="'+b.id+'">'+b.title+'</button>').join('');
nav.querySelectorAll('button').forEach(b=>b.onclick=()=>focusBoard(b.dataset.screenLink));document.querySelector('aside').append(nav);
const group=document.createElement('optgroup');group.label=title;group.innerHTML=selected.map(b=>'<option value="'+b.id+'">'+b.title+'</option>').join('');document.querySelector('#board-picker').append(group);
const dialog=document.createElement('dialog');dialog.id='home-prompt-dialog';dialog.setAttribute('aria-labelledby','home-prompt-title');
dialog.innerHTML='<h2 id="home-prompt-title">홈 지도 · AI 프롬프트</h2><label for="home-prompt-text">화면 캡처와 함께 전달할 디자인 정보</label><textarea id="home-prompt-text" readonly></textarea><p role="status"></p><div class="button-dialog-actions"><button data-close>닫기</button><button data-copy disabled>프롬프트 복사</button></div>';
document.body.append(dialog);
let trigger;
const text=dialog.querySelector('textarea'),status=dialog.querySelector('[role="status"]'),copy=dialog.querySelector('[data-copy]');
let request=0;
document.querySelectorAll('[data-home-prompt]').forEach(b=>b.onclick=async()=>{trigger=b;const infoKind=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-store-info'?'info':(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-store-location'?'location':'';const reviewKind=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-review-list'?'list':(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-review-photo'?'photo':'';const isReviews=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-store-reviews';const eventKind=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-event-list'?'list':(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-event-detail'?'detail':'';const newsKind=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-news-list'?'list':(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-news-detail'?'detail':'';const updateKind=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-store-news'?'news':(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-store-event'?'event':'';const serviceKind=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-store-reservation'?'reservation':(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-store-waiting'?'waiting':'';const isDetail=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-menu-detail';const isFull=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-full-menu';const isMenu=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-main-menu';const isStore=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-store';const isNearby=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-nearby';const isCategory=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-category';const isSearch=(b.closest('.screen-page').dataset.source||b.closest('.screen-page').id)==='home-search';dialog.querySelector('h2').textContent=(infoKind?(infoKind==='info'?'매장 상세정보':'위치찾기'):reviewKind?(reviewKind==='list'?'포토 리뷰 전체 목록':'리뷰 사진 상세'):isReviews?'매장 리뷰':eventKind?(eventKind==='list'?'이벤트 전체 목록':'이벤트 상세'):newsKind?(newsKind==='list'?'소식 전체 목록':'소식 상세'):updateKind?(updateKind==='news'?'매장 소식':'매장 이벤트'):serviceKind?(serviceKind==='reservation'?'매장 예약':'매장 웨이팅'):isDetail?'메뉴 상세':isFull?'전체 메뉴':isMenu?'주요 메뉴':isStore?'매장 상세':isNearby?'근처 보기':isCategory?'업종 선택':isSearch?'매장 검색·검색 결과':'홈 지도')+' · AI 프롬프트';if(b.dataset.depthPrompt)dialog.querySelector('h2').textContent+=' · 입체감 개선안';const current=++request;dialog.showModal();text.value='';copy.disabled=true;status.textContent='디자인 정보를 불러오는 중입니다.';
 try{const paths=['../foundations/app-tokens.css','../components/shared.css','../components/button/button.css','../components/input/input.css','../components/search/search.css','../components/tabs-chips/tabs-chips.css','../components/app-shell/app-shell.css','../pages/home/home.css'];
 if(!b.dataset.depthPrompt)paths.push('../pages/home/depth-subtle.css');
 if(b.dataset.depthPrompt)paths.push(b.hasAttribute('data-depth-subtle')?'../pages/home/depth-subtle.css':'../pages/home/depth-proposals.css');
 if(infoKind)paths.push('../pages/home/store-info.css','../pages/home/store.css','../components/avatar/avatar.css','../components/surfaces/surfaces.css');
 if(reviewKind)paths.push('../pages/home/review-pages.css','../pages/home/store-reviews.css','../pages/home/store.css','../components/avatar/avatar.css','../components/surfaces/surfaces.css','../components/section-heading/section-heading.css');
 if(isReviews)paths.push('../pages/home/store-reviews.css','../pages/home/store.css','../components/avatar/avatar.css','../components/surfaces/surfaces.css','../components/section-heading/section-heading.css');
 if(eventKind)paths.push('../pages/home/event-pages.css','../pages/home/news-pages.css','../pages/home/store-updates.css','../pages/home/store.css','../components/avatar/avatar.css','../components/surfaces/surfaces.css','../components/section-heading/section-heading.css');
 if(newsKind)paths.push('../pages/home/news-pages.css','../pages/home/store-updates.css','../pages/home/store.css','../components/avatar/avatar.css','../components/surfaces/surfaces.css','../components/section-heading/section-heading.css');
 if(updateKind)paths.push('../pages/home/store-updates.css','../pages/home/store.css','../components/avatar/avatar.css','../components/section-heading/section-heading.css');
 if(serviceKind)paths.push('../pages/home/store-services.css','../pages/home/store.css','../components/avatar/avatar.css','../components/surfaces/surfaces.css','../components/section-heading/section-heading.css');
 if(isDetail)paths.push('../pages/home/menu-detail.css','../pages/home/store.css','../components/avatar/avatar.css','../components/selection/selection.css','../components/badges/badges.css');
 if(isFull)paths.push('../pages/home/full-menu.css','../pages/home/store.css','../components/avatar/avatar.css');
 if(isSearch)paths.push('../pages/home/search.css','../components/list-row/list-row.css');
 if(isCategory)paths.push('../pages/home/category.css','../components/sheet/sheet.css');
 if(isNearby)paths.push('../pages/home/nearby.css','../components/sheet/sheet.css','../components/avatar/avatar.css');
 if(isStore)paths.push('../pages/home/store.css','../components/avatar/avatar.css');
 if(isMenu)paths.push('../pages/home/store.css','../pages/home/main-menu.css','../components/avatar/avatar.css','../components/section-heading/section-heading.css');
 const css=await Promise.all(paths.map(async path=>{const r=await fetch(path);if(!r.ok)throw new Error(path);return '/* '+path+' */\n'+await r.text();}));
 if(current!==request)return;
 text.value='홈 지도 화면을 첨부 캡처와 CSS로 구현하세요. 기존 lib/0_pages/01_home/home.dart와 my_navermap.dart의 NaverMap, 검색, 카테고리 선택, 현 위치, 현 지도 위치 둘러보기, 패널 연결 동작을 유지하고 스타일만 적용합니다. 기획 OGGO_유저앱_UI개편_화면시안_260904.pptx 표기03페이지/PPT4번째에 따라 등록30일 이내 신규 회원점에 NEW를 표시합니다. 핀 그림을 가리지 않도록 위에 배치합니다. 등록일 데이터 필드는 기존 모델과 API를 확인하고 임의로 추정하지 않습니다. 하단은 홈·마이랜드·바코드·오지파크·내 정보의 공통 bottomNavigation입니다. 필터는 기존 store_category.dart의 전체·한식·중식·일식과 더보기 순서, 기존 단일 선택/더보기 동작을 유지합니다. 핀은 기존 assets/markers/MCI*.png를 사용합니다. 숫자 묶음은 기존 클러스터 로직을 유지합니다. 그림의 숫자·회원점·위치는 예시이며 하드코딩하지 않습니다. 배경은 네이버지도 공식 다운로드 이미지인 media/naver-mangwon.png를 사용한 정적 시안입니다. © NAVER Corp. 출처를 유지합니다. 배경 이미지를 실제 앱 지도 구현으로 사용하지 말고 기존 NaverMap을 유지하세요. 디자이너 PDF의 세 가지 핀 대안·업종별 신규색·즐겨찾기 변경·조이바 변경은 이번 범위에 포함하지 않습니다. 정적 시안에 검색/위치권한/지도 조작을 구현하지 않습니다. 렌더러: design-system/pages/home/render.mjs. 공통 검색창·칩·버튼·하단탭과 토큰을 재사용하세요.\n\n'+css.join('\n\n');if(isSearch)text.value=searchPrompt+'\n\n'+css.join('\n\n');if(isCategory)text.value=categoryPrompt+'\n\n'+css.join('\n\n');if(isNearby)text.value=nearbyPrompt+'\n\n'+css.join('\n\n');if(isStore)text.value=storePrompt+'\n\n'+css.join('\n\n');if(isMenu)text.value=mainMenuPrompt+'\n\n'+css.join('\n\n');if(isFull)text.value=fullMenuPrompt+'\n\n'+css.join('\n\n');if(isDetail)text.value=menuDetailPrompt+'\n\n'+css.join('\n\n');if(serviceKind)text.value=(serviceKind==='reservation'?'매장 예약 영역입니다. ':'매장 웨이팅 영역입니다. ')+servicePrompt+'\n\n'+css.join('\n\n');if(updateKind)text.value=(updateKind==='news'?'매장 소식 영역입니다. ':'매장 이벤트 영역입니다. ')+updatesPrompt+'\n\n'+css.join('\n\n');if(newsKind)text.value=(newsKind==='list'?'소식 전체 목록입니다. ':'소식 상세입니다. ')+newsPagesPrompt+'\n\n'+css.join('\n\n');if(eventKind)text.value=(eventKind==='list'?'이벤트 전체 목록입니다. ':'이벤트 상세입니다. ')+eventPagesPrompt+'\n\n'+css.join('\n\n');if(isReviews)text.value=storeReviewsPrompt+'\n\n'+css.join('\n\n');if(reviewKind)text.value=(reviewKind==='list'?'포토 리뷰 전체 목록입니다. ':'리뷰 사진 상세입니다. ')+reviewPagesPrompt+'\n\n'+css.join('\n\n');if(infoKind)text.value=storeInfoPrompt+'\n\n'+css.join('\n\n');if(isStore||isMenu||isFull||isDetail||infoKind)text.value='표시 콘텐츠는 public-store-data.mjs의 개발 DB 공개 매장 스냅샷을 사용합니다. 등록 정보와 별도 상태 예시를 구분하며 신규 기능은 추가하지 않습니다.\n\n'+text.value;if(b.dataset.depthPrompt)text.value='입체감 개선 비교안입니다. 기존 내용은 유지하고 최상위 화면에 og-depth-proposal 클래스를 적용해 아래 비교안 CSS가 작동하도록 하세요. 기존 시안과 개선안을 동시에 덮어쓰지 마세요.\n\n'+text.value;if(b.hasAttribute('data-depth-subtle'))text.value=text.value.replace('og-depth-proposal 클래스를','og-depth-subtle 클래스를');if(b.hasAttribute('data-adopted-depth'))text.value=text.value.replace('입체감 개선 비교안입니다.','선택된 B안이 적용된 기본 시안입니다.');copy.disabled=false;status.textContent='복사할 준비가 되었습니다.';
 }catch{if(current===request)status.textContent='불러오지 못했습니다. 닫은 뒤 다시 열어 주세요.';}
});
dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{request++;trigger.focus({preventScroll:true});});
copy.onclick=async()=>{try{await navigator.clipboard.writeText(text.value);status.textContent='복사했습니다.';}catch{text.focus();text.select();status.textContent='선택된 내용을 직접 복사해 주세요.';}};
