import {surface as sharedSurface} from '../components/surfaces/render.mjs';
import {listRow,divider as renderDivider} from '../components/index.mjs';
import {specimenAttributes} from './specimen-utils.mjs';
{
 const board=document.createElement('section');board.id='list-row';board.className='board';
 const icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 4h14v17l-3-2-4 2-4-2-3 2zM8 8h8M8 12h8"/></svg>';
 const row=(title,{attrs='',cls='',...props}={})=>listRow({title,...props,iconHTML:icon,attributes:specimenAttributes(attrs),className:cls});
 const divider=renderDivider({inset:true});
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / LIST ROW</span><h1>목록 행</h1><p>제목은 왼쪽에, 값과 이동 표시는 오른쪽에 맞춥니다.</p></div>'+
 '<section id="row-navigation-specimen" class="row-section"><div class="row-heading"><h2>기본형·설명형</h2><button data-field-prompt="row-navigation-specimen">AI 프롬프트</button></div><div class="row-stage">'+sharedSurface({contentHTML:''+row('공지사항',{attrs:'id="row-live"'})+divider+row('자주 묻는 질문',{description:'서비스 이용 중 궁금한 내용을 확인하세요.'})+''})+'</div><p id="row-status" class="row-note" role="status">항목을 눌러 반응을 확인할 수 있습니다.</p><p class="row-note">최소 높이 56px · 좌우·상하 여백 16px · 제목 16px · 설명 13px. 제목과 설명 사이 간격은 4px입니다.</p></section>'+
 '<section id="row-media-specimen" class="row-section"><div class="row-heading"><h2>아이콘·썸네일형</h2><button data-field-prompt="row-media-specimen">AI 프롬프트</button></div><div class="row-stage">'+sharedSurface({contentHTML:''+row('이용 내역',{leading:'icon'})+divider+row('최근 방문 매장',{leading:'thumbnail',description:'회원점명 · 방문 내역 확인'})+''})+'</div><p class="row-note">아이콘 24px / 영역 너비 48px · 썸네일 48px · 제목과 간격 12px. 같은 목록에서는 이미지 영역과 글자 시작점을 맞춥니다.</p></section>'+
 '<section id="row-value-specimen" class="row-section"><div class="row-heading"><h2>우측 정보형</h2><button data-field-prompt="row-value-specimen">AI 프롬프트</button></div><div class="row-stage">'+sharedSurface({contentHTML:''+row('총 보유 마일리지',{value:'16,000 M',interactive:false,attrs:'id="row-information"'})+divider+row('앱 버전',{value:'1.0.0',interactive:false})+''})+'</div><h3>긴 내용</h3><div class="row-stage">'+row('오지고랜드 베이커리와 커피 서울숲직영점',{description:'마일리지 적립 내역',value:'+1,000 M',interactive:false,attrs:'id="row-long"'})+'</div><p class="row-note">긴 제목은 줄바꿈합니다. 공간이 부족하면 우측 값을 다음 줄에 배치합니다. 이동하지 않는 정보에는 화살표를 붙이지 않습니다.</p></section>'+
 '<section class="row-section"><h2>상태</h2><div class="row-states">'+[['마우스 오버','is-hover',''],['포커스','is-focus',''],['눌림','is-pressed',''],['비활성','','id="row-disabled" disabled']].map(([title,cls,attrs])=>'<div><h3>'+title+'</h3>'+row('이용 내역',{cls,attrs,description:attrs?'현재 이용할 수 없습니다.':''})+'</div>').join('')+'</div></section><h2>사용 기준</h2><ul class="rules-list"><li>목록 행은 평면으로 두고 바깥 카드에만 그림자를 사용합니다.</li><li>행 전체가 이동 버튼이면 안쪽에 별도 버튼을 넣지 않습니다.</li><li>정보만 보여주는 행에는 눌림 효과와 포커스를 넣지 않습니다.</li><li>불러오는 중·오류·빈 목록은 목록 전체의 안내 영역에서 표시합니다.</li></ul>';
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='list-row';nav.textContent='목록 행';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('목록 행','list-row'));
}
