import {surface as sharedSurface} from '../components/surfaces/render.mjs';
import {loading,loadingRow,loadingCard,surface} from '../components/index.mjs';
{
 const board=document.createElement('section');board.id='loading';board.className='board';
 const row=(title,subtitle,shape,symbol)=>surface({contentHTML:loadingRow({title,subtitle,shape,symbol,className:'loading-example'})});
 board.innerHTML=`<div class="board-heading"><span>COMPONENTS / LOADING</span><h1>로딩·스켈레톤</h1><p>기다리는 동안에도 내용이 들어올 자리를 유지합니다.</p></div>
 <section class="loading-section" id="loading-spinner-specimen"><div class="loading-heading"><h2>로딩 표시</h2><button data-field-prompt="loading-spinner-specimen">AI 프롬프트</button></div><div class="loading-stage"><div class="loading-spinner-samples">${loading()}${loading({label:'처리 중',size:'small'})}</div></div><p class="loading-note">기본 24px · 작은 표시 16px · 문구와 간격 8px. 단색 블루를 사용합니다.</p><ul class="rules-list"><li>짧은 처리 상태는 작은 로딩 표시와 문구로 알립니다.</li><li>진행률을 알 수 없을 때 임의의 퍼센트를 표시하지 않습니다.</li><li>목록이나 카드처럼 모양이 정해진 영역에는 아래 스켈레톤을 사용합니다.</li></ul></section>
 <section class="loading-section" id="loading-skeleton-specimen"><div class="loading-heading"><h2>스켈레톤</h2><button data-field-prompt="loading-skeleton-specimen">AI 프롬프트</button></div><label class="loading-controls" for="loading-state">표시 상태<select id="loading-state"><option value="loading">불러오는 중</option><option value="ready">내용 표시</option></select></label><p id="loading-status" class="loading-note" role="status">내용을 불러오는 중입니다.</p><div class="loading-stage"><div><h3>프로필</h3>${row('맑은 땅콩 님','프로필 캐릭터 선택','circle','face')}</div><div><h3>목록</h3>${row('회원점명','최근 방문 매장','square','storefront')}</div><div><h3>정보 카드</h3>${sharedSurface({contentHTML:`${loadingCard({label:'마일리지',title:'사용 가능 마일리지',amount:'15,000 M',caption:'총 보유 16,000 M',className:'loading-example'})}`})}</div></div><ul class="rules-list"><li>이미지·제목·본문 자리를 연한 회색 면으로 표시합니다. 글자마다 잘게 나누지 않습니다.</li><li>입체감은 바깥 카드에만 주고, 회색 면에는 테두리와 그림자를 넣지 않습니다.</li><li>밝기만 천천히 바뀝니다. 움직임 줄이기 설정에서는 정지된 면으로 표시합니다.</li><li>내용이 나타날 때 카드 크기와 시작 위치를 유지합니다.</li><li>기다림이 끝나면 스켈레톤을 없애고 내용이나 결과 안내를 표시합니다.</li></ul></section>`;
 document.querySelector('#world').append(board);
 const nav=document.createElement('button');nav.dataset.board='loading';nav.textContent='로딩·스켈레톤';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('로딩·스켈레톤','loading'));
}
