const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});
 await p.goto('http://127.0.0.1:4173/design-system/canvas/#my-info-password');await p.waitForFunction(()=>document.querySelector('#viewport')?.getAttribute('aria-busy')==='false');assert.equal(await p.locator('#my-info-password .og-password').count(),5);assert.equal(await p.locator('[data-review-go="board-my-info-password"]').count(),1);
 await p.locator('#my-info-password [data-screen-prompt]').click({force:true});await p.waitForFunction(()=>document.querySelector('#screen-prompt-text').value.includes('.og-pin-keys'));assert.match(await p.locator('#screen-prompt-text').inputValue(),/pin_create_page.dart/);
 await p.goto('http://127.0.0.1:4173/design-system/pages/my-info/');await p.evaluate(async()=>{const l=document.createElement('link');l.rel='stylesheet';l.href='/design-system/pages/my-info/password.css';document.head.append(l);await new Promise(r=>l.onload=r);const s=document.createElement('style');s.textContent='html,body{margin:0;padding:0;overflow-x:clip}';document.head.append(s);});
 for(const width of [320,375,414,768])for(let state=0;state<5;state++){
  await p.setViewportSize({width,height:820});await p.evaluate(async state=>{const {passwordBoard}=await import('/design-system/pages/my-info/password.mjs');const w=document.createElement('div');w.innerHTML=passwordBoard();document.body.replaceChildren(w.querySelectorAll('.og-password')[state]);await document.fonts.ready;},state);
  const result=await p.evaluate(()=>{const root=document.querySelector('.og-password-content'),keys=[...document.querySelectorAll('.og-pin-key')];return {fits:root.scrollWidth<=root.clientWidth+1,keys:keys.length,touch:keys.every(n=>{const r=n.getBoundingClientRect();return r.width>=44&&r.height>=44&&r.bottom<=800}),missing:[...new Set([...Array.from([...document.styleSheets].find(s=>s.href?.endsWith('/password.css')).cssRules).map(r=>r.cssText).join('').matchAll(/var\((--[^),]+)/g)].map(m=>m[1]))].filter(t=>!getComputedStyle(document.documentElement).getPropertyValue(t).trim())};});assert.ok(result.fits);assert.equal(result.keys,12);assert.ok(result.touch);assert.deepEqual(result.missing,[]);
  if(width===320||width===375)await p.screenshot({path:'/private/tmp/password-'+state+'-'+width+'.png'});
 }
 console.log('PASS password: five states, four widths, keypad geometry, prompt and review');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
