const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});
 await p.goto('http://127.0.0.1:4173/design-system/canvas/#my-info-policy-detail');await p.waitForFunction(()=>document.querySelector('#viewport')?.getAttribute('aria-busy')==='false');
 assert.equal(await p.locator('#my-info-policy-detail .og-policy-detail').count(),2);assert.equal(await p.locator('[data-review-go="board-my-info-policy-detail"]').count(),1);
 await p.locator('#my-info-policy-detail [data-screen-prompt]').click({force:true});await p.waitForFunction(()=>document.querySelector('#screen-prompt-text').value.includes('.og-policy-webview-frame'));assert.match(await p.locator('#screen-prompt-text').inputValue(),/policy_datail.dart/);
 await p.goto('http://127.0.0.1:4173/design-system/pages/my-info/');await p.evaluate(async()=>{const l=document.createElement('link');l.rel='stylesheet';l.href='/design-system/pages/my-info/policy-detail.css';document.head.append(l);await new Promise(r=>l.onload=r);const s=document.createElement('style');s.textContent='html,body{margin:0;padding:0;overflow-x:clip}';document.head.append(s);});
 for(const width of [320,375,414,768])for(const state of [0,1]){
  await p.setViewportSize({width,height:820});await p.evaluate(async state=>{const {policyDetailBoard}=await import('/design-system/pages/my-info/policy-detail.mjs');const w=document.createElement('div');w.innerHTML=policyDetailBoard();document.body.replaceChildren(w.querySelectorAll('.og-policy-detail')[state]);await document.fonts.ready;},state);
  const result=await p.evaluate(()=>{const doc=document.querySelector('.og-policy-document'),frame=document.querySelector('.og-policy-webview-frame'),header=document.querySelector('.og-app-bar'),title=header.querySelector('h2'),back=header.querySelector('button');const before=header.getBoundingClientRect().top;doc.scrollTop=100;return {fits:doc.scrollWidth<=doc.clientWidth+1,padding:getComputedStyle(frame).padding,overlap:back.getBoundingClientRect().right>title.getBoundingClientRect().left,scrolls:doc.scrollTop>0,headerFixed:header.getBoundingClientRect().top===before};});assert.ok(result.fits);assert.equal(result.padding,'16px');assert.equal(result.overlap,false);assert.ok(result.headerFixed);if(state===1)assert.ok(result.scrolls);
  await p.evaluate(()=>document.querySelector('.og-policy-document').scrollTop=0);if(width===320||width===375)await p.screenshot({path:'/private/tmp/policy-detail-'+state+'-'+width+'.png'});
 }
 console.log('PASS policy detail: four widths, header alignment, 16px inset, document scroll, prompt and review');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
