import {surface as sharedSurface} from '../components/surfaces/render.mjs';
import {progress,mileage} from '../components/progress/render.mjs';
{
 const board=document.createElement('section');board.id='progress';board.className='board';
 const track=(value,label)=>progress({value,label});
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / PROGRESS</span><h1>진행 바·게이지</h1><p>바는 얇게 유지하고, 숫자와 구간 설명은 바 밖에 표시합니다.</p></div>'+
 '<section id="progress-basic-specimen" class="progress-section"><div class="progress-heading"><h2>기본 진행 바</h2><button data-field-prompt="progress-basic-specimen">AI 프롬프트</button></div><div class="progress-stage">'+sharedSurface({contentHTML:''+progress({value:40,label:'진행률',id:'progress-live',labelId:'progress-label'})+'<div class="og-progress-caption"><span>0%</span><span>100%</span></div>'})+'</div><label class="progress-controls" for="progress-state">표시 상태<select id="progress-state"><option value="0">시작 전 · 0%</option><option value="40" selected>진행 중 · 40%</option><option value="100">완료 · 100%</option><option value="loading">불러오는 중</option></select></label><p class="progress-note">바 높이 8px · 양 끝은 둥글게 · 숫자와 간격 8px. 일반 진행률에는 단색 블루를 사용합니다.</p><div class="progress-state-list"><div>'+track(0,'시작 전')+'</div><div>'+track(40,'진행 중')+'</div><div>'+track(100,'완료')+'</div></div><ul class="rules-list"><li>0%에서도 배경 바를 유지하고, 완료는 100% 숫자로 표시합니다.</li><li>값을 불러오는 동안은 회색 바와 안내 문구를 보여줍니다. 0%로 표시하지 않습니다.</li><li>바 자체를 누르거나 끌어서 값을 바꾸지 않습니다.</li></ul></section>'+
 '<section id="progress-mileage-specimen" class="progress-section"><div class="progress-heading"><h2>마일리지 게이지</h2><button data-field-prompt="progress-mileage-specimen">AI 프롬프트</button></div><div class="progress-stage">'+sharedSurface({contentHTML:''+mileage({available:15000,total:16000,max:20000,ids:{available:'mileage-available',total:'mileage-total',track:'mileage-track',end:'mileage-end'}})+''})+'</div><label class="progress-controls" for="mileage-example">보유 금액 예시<select id="mileage-example"><option value="16000">16,000 M</option><option value="15000">15,000 M · 단위 도달</option><option value="1000">1,000 M · 사용 전</option><option value="0">0 M</option><option value="loading">불러오는 중</option></select></label><p class="progress-note">사용 가능 금액은 총 보유 금액에 포함됩니다. 그라데이션은 사용 가능 금액, 차분한 블루는 나머지 보유 금액을 표시합니다.</p><ul class="rules-list"><li>15,000 M + 1,000 M = 총 보유 16,000 M입니다. 두 금액을 중복해서 더하지 않습니다.</li><li>20,000 M은 이 게이지의 표시 범위입니다. 적립 목표나 보유 한도를 뜻하지 않습니다.</li><li>사용 가능 금액은 총 보유에서 5,000 M 단위로 표시합니다. 바의 끝값은 보유 금액 이상의 가장 가까운 5,000 M 단위입니다. 정확히 도달하면 바가 가득 찹니다.</li><li>0 M은 0~5,000 M의 빈 바로 표시합니다. 불러오는 중에는 금액을 —로 표시하며, 0 M과 구분합니다.</li><li>게이지에 그림자나 반복 애니메이션을 넣지 않습니다. 입체감은 바깥 카드에서 표현합니다.</li></ul></section>';
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='progress';nav.textContent='진행 바·게이지';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('진행 바·게이지','progress'));
}
