import {quantity} from '../components/quantity/render.mjs';
{
 const board=document.createElement('section');board.id='quantity';board.className='board';
 const control=(id,value=2,props={})=>quantity({id,value,descriptionId:props.locked?'quantity-locked-reason':'',...props});
 board.innerHTML=`<div class="board-heading"><span>COMPONENTS / QUANTITY</span><h1>수량 조절</h1><p>현재 수량을 가운데에 두고, 양옆 버튼으로 한 개씩 조절합니다.</p></div>
 <section class="quantity-section" id="quantity-basic-specimen"><div class="quantity-heading"><h2>기본형</h2><button data-field-prompt="quantity-basic-specimen">AI 프롬프트</button></div><div class="quantity-stage"><div class="quantity-row"><strong>주문 수량</strong>${control('quantity-live',1)}</div><p class="quantity-note">1개부터 5개까지 조절해 보세요.</p></div><p class="quantity-note">버튼 터치 영역 48px · 아이콘 20px · 숫자 16px / 행간 24px · 모서리 12px.</p><ul class="rules-list"><li>한 번 누를 때마다 1개씩 바뀝니다. 길게 눌러도 연속으로 증가하지 않습니다.</li><li>숫자는 직접 입력하지 않습니다. 가운데 정렬과 숫자 폭을 유지합니다.</li><li>밝은 윗면과 얇은 테두리로 하나의 컨트롤처럼 묶습니다. 누른 버튼에만 가벼운 눌림을 줍니다.</li></ul></section>
 <section class="quantity-section" id="quantity-states-specimen"><div class="quantity-heading"><h2>상태</h2><button data-field-prompt="quantity-states-specimen">AI 프롬프트</button></div><div class="quantity-grid"><div><h3>최소 수량</h3>${control('quantity-min',1)}<p>줄이기 버튼을 비활성으로 표시합니다.</p></div><div><h3>최대 수량</h3>${control('quantity-max',5)}<p>늘리기 버튼을 비활성으로 표시합니다.</p></div><div><h3>변경 불가</h3>${control('quantity-locked',2,{locked:true})}<p id="quantity-locked-reason">현재는 수량을 변경할 수 없습니다.</p></div><div><h3>두 자리 수량</h3>${control('quantity-digits',99,{max:99})}<p>숫자가 길어져도 양옆 버튼 크기는 유지합니다.</p></div><div><h3>마우스 오버</h3>${control('quantity-hover',2,{state:'is-hover'})}</div><div><h3>키보드 포커스</h3>${control('quantity-focus',2,{state:'is-focus'})}</div><div><h3>눌림</h3>${control('quantity-pressed',2,{state:'is-pressed'})}</div></div><ul class="rules-list"><li>최소·최대 수량에서는 해당 방향의 버튼만 비활성으로 표시합니다.</li><li>수량을 바꿀 수 없으면 두 버튼을 모두 비활성으로 표시하고 이유를 가까이에 둡니다.</li><li>최소 수량에서 줄이기 버튼을 눌러도 상품이 삭제되지 않습니다.</li><li>상품 이름과 함께 배치하고, 좁은 공간에서는 수량 조절을 다음 줄로 내립니다.</li></ul></section>`;
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='quantity';nav.textContent='수량 조절';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('수량 조절','quantity'));
}
