const{chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});
 let release;const gate=new Promise(r=>release=r);
 await p.route('**/area-layout.js*',async route=>{await gate;await route.continue()});
 await p.goto('http://127.0.0.1:4173/design-system/canvas/',{waitUntil:'commit'});
 await p.waitForSelector('#canvas-loading');
 assert.equal(await p.locator('#world').evaluate(n=>getComputedStyle(n).opacity),'0','no initial canvas flash');
 release();await p.waitForFunction(()=>document.querySelector('#viewport').getAttribute('aria-busy')==='false');
 await p.locator('[data-board="color"]').click();
 assert.ok(await p.locator('#review-reservation-date').evaluate(n=>!!n.closest('.canvas-offscreen')),'nested review starts in a skipped board');
 await p.locator('#review-toggle').click();const pendingCount=await p.locator('[data-review-row]').count();assert.ok(pendingCount>=10);
 await p.locator('[data-review-go="reservation-date"]').click();
 const target=p.locator('#review-reservation-date');assert.ok(await target.isVisible());const box=await target.boundingBox();assert.ok(box.y>=70&&box.y<500,'jumps to nested example, not page top');
 await p.locator('#review-toggle').click();await p.locator('[data-review-complete="reservation-date"]').click();assert.equal(await p.locator('[data-review-row]').count(),pendingCount-1);
 await p.locator('[data-review-tab="done"]').click();assert.equal(await p.locator('[data-review-row]').count(),1);
 await p.reload();await p.waitForFunction(()=>document.querySelector('#viewport')?.getAttribute('aria-busy')==='false');
 await p.locator('#review-toggle').click();assert.equal(await p.locator('[data-review-row]').count(),pendingCount-1);
 await p.locator('[data-review-tab="done"]').click();await p.locator('[data-review-reopen="reservation-date"]').click();
 await p.locator('[data-review-tab="pending"]').click();assert.equal(await p.locator('[data-review-row]').count(),pendingCount);
 await p.locator('[data-review-close]').click();
 await p.locator('[data-board="color"]').click();
 await p.locator('#color > .canvas-review-controls [data-review-set="pending"]').click();
 await p.locator('#review-toggle').click();assert.equal(await p.locator('[data-review-row]').count(),pendingCount+1);
 await p.locator('[data-review-complete="board-color"]').click();
 await p.locator('[data-review-tab="done"]').click();assert.equal(await p.locator('[data-review-row]').count(),1);
 await p.locator('[data-review-reopen="board-color"]').click();
 await p.locator('[data-review-tab="pending"]').click();assert.equal(await p.locator('[data-review-row]').count(),pendingCount+1);
 await p.locator('[data-review-complete="board-my-info-notices"]').click();
 await p.reload();await p.waitForFunction(()=>document.querySelector('#viewport')?.getAttribute('aria-busy')==='false');
 await p.locator('#review-toggle').click();
 assert.equal(await p.locator('[data-review-go="board-my-info-notices"]').count(),0,'completed auto entry stays completed after reload');
 assert.equal(await p.locator('[data-review-go="board-my-info-order-detail"]').count(),1);
 assert.equal(await p.locator('[data-review-go="board-my-info-review-history"]').count(),1);
 assert.equal(await p.locator('[data-review-go="board-my-info-notice-detail"]').count(),1,'newly completed page auto-enrolled');
 assert.equal(await p.locator('[data-review-go="board-my-info-character"]').count(),1,'deferred page with provenance notes is reviewable');
 await p.locator('[data-review-tab="done"]').click();
 assert.equal(await p.locator('[data-review-go="board-my-info-notices"]').count(),1);
 await p.locator('[data-review-reopen="board-my-info-notices"]').click();
 await p.locator('[data-review-tab="pending"]').click();
 await p.locator('#review-panel').screenshot({path:'/private/tmp/canvas-review-panel.png'});
 console.log('PASS: loading gate, automatic review entries, direct navigation, completion persistence and reopen');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
