const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});
 await p.goto('http://127.0.0.1:4173/design-system/canvas/#my-info-review-write');await p.waitForFunction(()=>document.querySelector('#viewport')?.getAttribute('aria-busy')==='false');
 assert.equal(await p.locator('#my-info-review-write .og-review-write').count(),7);assert.equal(await p.locator('[data-review-go="board-my-info-review-write"]').count(),1);
 await p.locator('#my-info-review-write [data-screen-prompt]').click({force:true});await p.waitForFunction(()=>document.querySelector('#screen-prompt-text').value.includes('.og-write-body'));assert.match(await p.locator('#screen-prompt-text').inputValue(),/multiphoto_review_page.dart/);
 await p.goto('http://127.0.0.1:4173/design-system/pages/my-info/');await p.evaluate(async()=>{const l=document.createElement('link');l.rel='stylesheet';l.href='/design-system/pages/my-info/review-write.css';document.head.append(l);await new Promise(r=>l.onload=r);const s=document.createElement('style');s.textContent='html,body{margin:0;padding:0;overflow-x:clip}';document.head.append(s);});
 for(const width of [320,375,414,768])for(let state=0;state<7;state++){
  await p.setViewportSize({width,height:820});await p.evaluate(async state=>{const {reviewWriteBoard}=await import('/design-system/pages/my-info/review-write.mjs');const w=document.createElement('div');w.innerHTML=reviewWriteBoard();document.body.replaceChildren(w.querySelectorAll('.og-review-write')[state]);await document.fonts.ready;},state);
  const result=await p.evaluate(()=>{const root=document.querySelector('.og-review-write'),body=root.querySelector('.og-write-body'),footer=root.querySelector('.og-write-footer');return {fits:body.scrollWidth<=body.clientWidth+1,footer:!!footer,footerFits:!footer||footer.getBoundingClientRect().bottom<=801,rows:root.querySelector('textarea').rows,missing:[...new Set([...Array.from([...document.styleSheets].find(s=>s.href?.endsWith('/review-write.css')).cssRules).map(r=>r.cssText).join('').matchAll(/var\((--[^),]+)/g)].map(m=>m[1]))].filter(t=>!getComputedStyle(document.documentElement).getPropertyValue(t).trim())};});assert.ok(result.fits);assert.equal(result.footer,[1,2,3,5].includes(state));assert.ok(result.footerFits);assert.equal(result.rows,state===2?7:5);assert.deepEqual(result.missing,[]);
  if(width===375)await p.screenshot({path:'/private/tmp/review-write-'+state+'.png'});
 }
 console.log('PASS review-write: seven states, four widths, conditional footer, textarea, tokens, prompt and review');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
