import {searchField} from '../components/search/render.mjs';
import {specimenAttributes} from './specimen-utils.mjs';
/* Local sample dataset only. Requests are simulated; no network/storage is used. */
{
 const board=document.createElement('section');board.id='search';board.className='board';board.dataset.component='search';
 const staticInput=(id,label,attr='',className='')=>{const {value='',...attributes}=specimenAttributes(attr);return searchField({id,label,value,attributes,className,hint:attributes.disabled?'입력창과 검색 기능을 비활성 상태로 표시합니다.':'검색어는 유지하고 레이블은 항상 표시합니다.'});};
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / SEARCH</span><h1>검색창</h1><p>입력과 검색 실행을 분리하고, 결과 상태는 아래에 표시합니다.</p></div><section id="search-specimen"><div class="input-section-header"><h2>검색 입력</h2><button data-field-prompt="search-specimen">AI 프롬프트</button></div><div class="search-demo">'+searchField({id:'search-query',label:'매장 검색',placeholder:'예: 카페, 식당',hint:'Enter 또는 검색 버튼으로 실행합니다.',submit:true,formId:'search-form',helpId:'search-help',clearId:'search-clear',submitId:'search-submit',attributes:{enterkeyhint:'search',autocomplete:'off','aria-invalid':'false'}})+'<label class="search-demo-controls"><input id="search-failure" type="checkbox">오류 상태 보기</label><div id="search-results" class="search-preview-results" aria-busy="false"><p id="search-status" role="status">검색 전 · 카페 또는 식당을 입력해 보세요.</p><ul id="search-list"></ul><button type="button" id="search-retry" class="og-text-button" hidden>다시 검색</button></div></div><p class="input-demo-note">검색 전·검색 중·결과 없음·오류 안내를 결과 영역에서 보여줍니다.</p><h2>기본 상태</h2><div class="search-state-list">'+staticInput('search-empty','기본')+staticInput('search-focused','포커스','value="카페"','is-focus')+staticInput('search-filled','입력 완료','value="식당"')+staticInput('search-disabled','비활성','disabled')+'</div><h2>실행과 결과 규칙</h2><ul class="rules-list"><li>검색 입력은 높이 48 · 모서리 12 · 본문 16 / 행간 24입니다. 검색 버튼은 입력창과 같은 높이를 사용합니다.</li><li>돋보기는 20, 지우기 버튼의 터치 영역은 48입니다. 내용이 없어도 오른쪽 공간은 유지합니다.</li><li>빈 값·공백만 있는 값은 실행하지 않고 입력창 아래에서 안내합니다. 한글 조합 중 Enter는 검색을 실행하지 않습니다.</li><li>검색 중에도 입력·지우기는 가능합니다. 검색어를 바꾸거나 지우면 이전 결과도 지웁니다.</li><li>결과 없음은 검색어 오류가 아닙니다. 입력값은 유지하고 결과 영역에서 다른 검색어를 안내합니다.</li><li>실패 시 검색어를 유지하고 다시 검색을 제공합니다. 마지막 요청의 결과만 표시합니다.</li><li>좁은 가용 폭에서는 검색 버튼을 다음 줄 전체 폭으로 배치합니다. 키보드 검색 액션도 같은 동작으로 연결합니다.</li></ul></section>';
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='search';nav.textContent='검색창';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('검색창','search'));
}
