import {surface as sharedSurface} from '../components/surfaces/render.mjs';
import {sectionHeading,textButton} from '../components/index.mjs';
{
 const board=document.createElement('section');board.id='section-heading';board.className='board';
 const heading=(title,props={})=>sectionHeading({title,...props,infoId:props.infoButton?'heading-info':undefined,helpId:props.infoButton?'heading-help':undefined,actionId:props.id==='heading-with-action'?'heading-action':undefined});
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / SECTION HEADING</span><h1>섹션 제목</h1><p>정보 묶음의 시작을 알리고, 관련 동작은 오른쪽에 배치합니다.</p></div>'+
 '<section id="heading-basic-specimen" class="heading-section"><div class="heading-section-title"><h2>기본형</h2><button data-field-prompt="heading-basic-specimen">AI 프롬프트</button></div><div class="heading-stage">'+sharedSurface({contentHTML:''+heading('최근 방문')+'<div class="heading-content-sample">최근 방문한 회원점이 표시됩니다.</div>'})+'</div><p class="heading-note">제목 20px / 행간 28px / 굵기 700 · 제목과 본문 사이 16px. 제목 자체에는 그림자를 넣지 않습니다.</p></section>'+
 '<section id="heading-description-specimen" class="heading-section"><div class="heading-section-title"><h2>설명형</h2><button data-field-prompt="heading-description-specimen">AI 프롬프트</button></div><div class="heading-stage">'+sharedSurface({contentHTML:''+heading('마일리지 내역',{description:'적립하고 사용한 마일리지를 확인하세요.'})+''})+'</div><p class="heading-note">설명 14px / 행간 22px · 제목과 간격 8px. 설명은 한두 문장으로 짧게 쓰고, 길어지면 자연스럽게 줄바꿈합니다.</p></section>'+
 '<section id="heading-action-specimen" class="heading-section"><div class="heading-section-title"><h2>액션형·정보 아이콘</h2><button data-field-prompt="heading-action-specimen">AI 프롬프트</button></div><div class="heading-stage">'+sharedSurface({contentHTML:''+heading('마일리지',{action:'전체 보기',infoButton:true,id:'heading-with-action'})+'<p id="heading-help" class="og-heading-help" hidden>사용 가능 마일리지는 총 보유 마일리지에 포함됩니다.</p><div class="heading-content-sample">제목 옆 아이콘을 누르면 안내를 확인할 수 있습니다.</div>'})+'</div><p id="heading-status" class="heading-note" role="status">우측 버튼을 눌러 반응을 확인할 수 있습니다.</p><p class="heading-note">정보 아이콘 16px · 제목과 보이는 간격 8px · 터치 영역 48px. 아이콘은 제목의 세로 중앙에 맞춥니다. 우측 버튼은 13px로 제목보다 작게 표시합니다.</p><h3>긴 제목</h3><div class="heading-stage">'+sharedSurface({contentHTML:''+heading('최근 방문한 회원점과 이용 내역',{action:'전체 보기',id:'heading-long'})+''})+'</div><p class="heading-note">제목은 생략하지 않고 줄바꿈합니다. 공간이 부족하면 우측 버튼을 다음 줄 오른쪽으로 내려 배치합니다.</p></section>'+
 '<h2>우측 버튼 상태</h2><div class="heading-states">'+[['기본','',false],['마우스 오버','is-hover',false],['포커스','is-focus',false],['눌림','is-pressed',false],['비활성','',true]].map(([label,cls,disabled])=>'<div><span>'+label+'</span>'+textButton({label:'전체 보기',className:'og-heading-action '+cls,disabled})+'</div>').join('')+'</div><h2>사용 기준</h2><ul class="rules-list"><li>같은 화면의 섹션 제목은 크기와 왼쪽 시작점을 맞춥니다.</li><li>정보 아이콘과 우측 버튼은 서로 다른 터치 영역으로 구분합니다.</li><li>우측 버튼에는 현재 섹션과 관련된 동작 하나만 둡니다.</li><li>불러오는 중·오류·빈 상태는 제목을 바꾸지 않고 본문에서 안내합니다.</li></ul>';
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='section-heading';nav.textContent='섹션 제목';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('섹션 제목','section-heading'));
}
