import {choice as renderChoice,toggle as renderToggle} from '../components/selection/render.mjs';
/* Local interaction specimens only: no network request or saved preference. */
{
 const board=document.createElement('section');board.id='selection';board.className='board';board.dataset.component='selection';
 const choice=(id,label,{cls='',...props}={})=>renderChoice({id,label,className:cls,...props});
 const toggle=(id,label,{cls='',...props}={})=>renderToggle({id,label,className:cls,...props});
 const stateGrid=(prefix,type)=>'<div class="selection-state-grid">'+[
  ['미선택',{}],['선택',{checked:true}],['포커스',{cls:'is-focus',checked:true}],['마우스 오버',{cls:'is-hover'}],['비활성 · 미선택',{disabled:true}],['비활성 · 선택',{disabled:true,checked:true}]
 ].map(([title,props],i)=>'<div><h3>'+title+'</h3>'+(type==='switch'?toggle(prefix+i,'알림 받기',props):choice(prefix+i,'선택 항목',{...props,type,name:type==='radio'?prefix+i:''}))+'</div>').join('')+'</div>';
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / SELECTION</span><h1>선택 요소</h1><p>여러 개 선택 · 하나만 선택 · 즉시 켜고 끄기를 구분합니다.</p></div>'+
 '<section id="checkbox-specimen" class="selection-section"><div class="selection-heading"><h2>체크박스</h2><button data-field-prompt="checkbox-specimen">AI 프롬프트</button></div><div class="selection-demo"><fieldset class="og-choice-group"><legend>관심 소식 · 복수 선택</legend>'+choice('select-all','전체 선택')+'<hr>'+['이벤트 소식','마일리지 소식','서비스 소식'].map((label,i)=>choice('select-child-'+i,label)).join('')+choice('select-disabled','준비 중인 소식',{disabled:true,description:'아직 선택할 수 없는 항목입니다.'})+'</fieldset><p id="checkbox-status" class="og-choice-help" role="status">0 / 3개 선택</p></div>'+stateGrid('checkbox-state-','checkbox')+'<p class="selection-note">사각형 20 · 행 전체 터치 영역 최소 48 · 레이블 간격 8. 여러 항목을 독립적으로 선택합니다. 전체 선택은 활성 항목에만 적용하며, 일부만 선택하면 가로선으로 부분 선택을 표시합니다.</p></section>'+
 '<section id="radio-specimen" class="selection-section"><div class="selection-heading"><h2>라디오</h2><button data-field-prompt="radio-specimen">AI 프롬프트</button></div><div class="selection-demo"><fieldset class="og-choice-group"><legend>안내 수단 · 단일 선택</legend>'+choice('radio-demo-0','앱 알림',{type:'radio',name:'contact-channel',checked:true})+choice('radio-demo-1','이메일',{type:'radio',name:'contact-channel'})+choice('radio-demo-2','문자',{type:'radio',name:'contact-channel',disabled:true,description:'현재 선택할 수 없는 항목입니다.'})+'</fieldset></div>'+stateGrid('radio-state-','radio')+'<p class="selection-note">원형 20 · 행 전체 터치 영역 최소 48. 같은 그룹에서는 하나만 선택합니다. 선택 자체를 완료·성공으로 표시하지 않습니다.</p></section>'+
 '<section id="switch-specimen" class="selection-section"><div class="selection-heading"><h2>스위치</h2><button data-field-prompt="switch-specimen">AI 프롬프트</button></div><div class="selection-demo">'+toggle('switch-live','소식 알림',{description:'현재 꺼짐'})+'<p id="switch-status" class="og-choice-help" role="status">스위치를 눌러 상태를 전환합니다.</p><div class="selection-simulation">'+choice('simulate-save-failure','오류 상태 보기',{description:'스위치를 전환하면 오류 안내를 확인할 수 있습니다.'})+'</div></div>'+stateGrid('switch-state-','switch')+'<p class="selection-note">트랙 44 × 28 · 손잡이 20 · 행 전체 터치 영역 최소 48. 켜짐은 오른쪽, 꺼짐은 왼쪽입니다. 클릭 또는 Space로 즉시 전환합니다. 저장 중에는 추가 조작을 막고, 실패하면 이전 상태로 되돌린 뒤 오류를 안내합니다. 다시 전환하면 재시도합니다.</p></section>'+
 '<h2>공통 사용 기준</h2><ul class="rules-list"><li>기본·선택·마우스 오버·키보드 포커스·누름·비활성을 구분합니다. 포커스는 지연 없이 표시합니다.</li><li>체크박스·라디오의 로딩·오류·완료는 해당 폼의 저장 결과로 안내합니다. 선택 기호를 오류나 성공 장식으로 바꾸지 않습니다.</li><li>긴 레이블은 줄바꿈하고 행 높이를 늘립니다. 클릭 영역과 별도의 상세보기 링크를 겹치지 않습니다.</li><li>비활성은 선택 상태와 무관합니다. 선택된 채 비활성인 경우에도 선택 표시를 유지합니다.</li></ul>';
 document.querySelector('#world').append(board);
 const nav=document.createElement('button');nav.dataset.board='selection';nav.textContent='선택 요소';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('선택 요소','selection'));
}
