import {bottomSheet,radio,tabs,tabPanel} from '../components/index.mjs';
{
 const board=document.createElement('section');board.id='sheet';board.className='board';
 const choices=[['recent','최신순'],['popular','인기순']];
 const choiceBody=prefix=>'<fieldset class="og-choice-group"><legend>게시글 정렬</legend>'+choices.map(([value,label],i)=>radio({id:prefix+'-choice-'+i,name:prefix+'-sort',label,checked:i===0,attributes:{value,'data-sheet-initial':i===0?true:undefined}})).join('')+'</fieldset>';
 const historyTabs=[['예약','event_note','예약 내역이 없습니다.'],['웨이팅','hourglass_empty','웨이팅 내역이 없습니다.'],['Q오더','receipt_long','주문 내역이 없습니다.'],['리뷰','rate_review','작성한 리뷰가 없습니다.']];
 const history=prefix=>tabs({id:prefix,label:'이용내역 종류',items:historyTabs.map(([label])=>label),className:'og-sheet-tabs'})+'<div class="og-sheet-body">'+historyTabs.map(([label,icon,message],i)=>tabPanel({id:prefix,index:i,className:'og-sheet-history',contentHTML:'<span class="material-icons" aria-hidden="true">'+icon+'</span><h3>'+message+'</h3><p>이용한 내역은 이곳에서 확인할 수 있습니다.</p>'})).join('')+'</div>';
 const historyPanel=id=>bottomSheet({id,size:'long',title:'이용내역',bodyHTML:history(id),bodyWrapped:false,action:'닫기',actionAttributes:{'data-sheet-close':true},headerAttributes:{'data-sheet-initial':true}});
 const panel=(title,bodyHTML,action,id)=>bottomSheet({id,title,bodyHTML,action,actionAttributes:{'data-sheet-apply':true}});
 board.innerHTML=`<div class="board-heading"><span>COMPONENTS / BOTTOM SHEET</span><h1>바텀시트</h1><p>현재 화면 위에서 선택하거나, 필요한 내용을 확인합니다.</p></div>
 <section class="sheet-section" id="sheet-choice-specimen"><div class="sheet-heading"><h2>커뮤니티 정렬</h2><button data-field-prompt="sheet-choice-specimen">AI 프롬프트</button></div><div class="sheet-stage">${panel('게시글 정렬',choiceBody('sheet-preview-choice'),'선택 적용','sheet-preview-choice')}</div><div class="sheet-actions"><button class="og-button" id="sheet-choice-open">정렬 열기</button><p id="sheet-choice-status" role="status" class="sheet-note">최신순</p></div><ul class="rules-list"><li>한 가지를 선택하고 하단 버튼으로 적용합니다.</li><li>적용하지 않고 닫으면 이전 선택을 유지합니다.</li><li>내용이 짧으면 필요한 높이만 차지합니다.</li></ul></section>
 <section class="sheet-section" id="sheet-scroll-specimen"><div class="sheet-heading"><h2>이용내역 · 탭형</h2><button data-field-prompt="sheet-scroll-specimen">AI 프롬프트</button></div><div class="sheet-stage">${historyPanel('sheet-preview-scroll')}</div><div class="sheet-actions"><button class="og-button" id="sheet-scroll-open">이용내역 열기</button></div><p class="sheet-note">상단 모서리 24px · 본문 여백 16px · 최대 높이 화면의 85%. 아래 버튼에는 안전 영역 여백을 더합니다.</p><ul class="rules-list"><li>예약·웨이팅·Q오더·리뷰를 탭으로 나눕니다. 제목·탭·닫기 버튼은 고정하고 내역만 스크롤합니다.</li><li>바깥 영역·닫기 버튼·Esc로 닫습니다. 뒤 화면은 누르거나 조작할 수 없습니다.</li><li>드래그로 높이를 바꾸는 손잡이는 표시하지 않습니다.</li><li>내역이 없으면 선택한 탭에 맞는 빈 상태를 보여줍니다. 탭은 방향키와 Home·End로도 전환합니다.</li></ul></section>`;
 board.querySelectorAll('.og-sheet-panel').forEach(example=>{example.inert=true;});
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='sheet';nav.textContent='바텀시트';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('바텀시트','sheet'));
}
