import {surface,menuTile,divider} from '../components/surfaces/render.mjs';
import {specimenAttributes} from './specimen-utils.mjs';
{
 const board=document.createElement('section');board.id='surfaces';board.className='board';
 const icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2zM9 7h6M9 11h6M9 15h3"/></svg>';
 const tile=(label,attrs='')=>menuTile({label,iconHTML:icon,attributes:specimenAttributes(attrs)});
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / SURFACE & DIVIDER</span><h1>카드·구분선</h1><p>정보는 카드로 묶고, 누를 수 있는 메뉴에는 얇은 두께를 줍니다.</p></div>'+
 '<section id="surface-specimen" class="surface-section"><div class="surface-heading"><h2>정보 카드와 평면 영역</h2><button data-field-prompt="surface-specimen">AI 프롬프트</button></div><div class="surface-stage">'+surface({attributes:{id:'surface-card'},contentHTML:'<h3>정보 카드</h3><p>마일리지·최근 방문처럼 하나로 묶어 읽는 정보에 사용합니다.</p>'})+''+surface({attributes:{id:'surface-flat'},depth:'flat',contentHTML:'<h3>평면 영역</h3><p>목록이나 안내 내용은 그림자 없이 선과 여백으로 구분합니다.</p>'})+'</div><p class="surface-note">안쪽 여백 16px · 모서리 20px · 테두리 1px. 정보 카드는 밝은 윗면과 짧고 부드러운 그림자로 띄웁니다.</p><ul class="rules-list"><li>내용이 늘어나면 카드 높이도 함께 늘어납니다.</li><li>카드 안에 카드를 겹칠 때는 안쪽을 평면으로 처리합니다.</li><li>정보를 담는 카드에는 눌림 효과를 넣지 않습니다.</li></ul></section>'+
 '<section id="tile-specimen" class="surface-section"><div class="surface-heading"><h2>메뉴 타일</h2><button data-field-prompt="tile-specimen">AI 프롬프트</button></div><div class="surface-stage"><div class="surface-tile-grid">'+[['기본',tile('이용 내역','id="menu-tile-live"')],['마우스 오버',tile('이용 내역','')],['포커스',tile('이용 내역','')],['눌림',tile('이용 내역','')],['비활성',tile('이용 내역','id="tile-disabled" disabled')]].map(([name,html])=>'<div>'+html+'<small>'+name+'</small></div>').join('')+'</div></div><p id="tile-status" class="surface-note" role="status">이용 내역을 눌러 반응을 확인할 수 있습니다.</p><p class="surface-note">모서리 12px · 하단 두께 2px · 아이콘 24px · 아이콘과 이름 사이 8px. 밝은 윗면과 얇은 하단 경계로 입체감을 표현합니다.</p><ul class="rules-list"><li>누르면 1px 내려가며 그림자가 짧아집니다.</li><li>비활성 메뉴는 그림자를 없애고, 사용할 수 없는 이유를 주변에 안내합니다.</li><li>불러오는 중·오류·완료는 이동한 화면의 내용에서 안내합니다.</li></ul></section>'+
 '<section id="divider-specimen" class="surface-section"><div class="surface-heading"><h2>구분선</h2><button data-field-prompt="divider-specimen">AI 프롬프트</button></div><h3>전체 너비</h3><div class="surface-divider-demo"><p>이용 안내</p>'+divider()+'<p>문의하기</p></div><h3>안쪽 여백</h3><div class="surface-divider-demo"><p>공지사항</p>'+divider({inset:true})+'<p>자주 묻는 질문</p></div><h3>세로 구분</h3><div class="surface-divider-demo surface-columns"><div><small>사용 가능</small><strong>15,000 M</strong></div>'+divider({vertical:true})+'<div><small>총 보유</small><strong>16,000 M</strong></div></div><p class="surface-note">선 두께 1px · 색상 app-edge. 안쪽 여백형은 좌우 16px를 띄웁니다. 세로선은 나란히 놓인 정보를 구분할 때 사용합니다.</p><ul class="rules-list"><li>구분선에는 그림자를 넣지 않습니다.</li><li>여백만으로 충분히 구분되면 선은 생략합니다.</li><li>정보를 세로로 쌓는 좁은 화면에서는 세로선도 가로선으로 바꿉니다.</li></ul></section>';
 // Merge forced state classes without duplicate class attributes.
 board.querySelectorAll('.surface-tile-grid>div').forEach((row,i)=>{if(i>0&&i<4)row.querySelector('button').classList.add(['','is-hover','is-focus','is-pressed'][i]);});
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='surfaces';nav.textContent='카드·구분선';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('카드·구분선','surfaces'));
}
