import {tabs,tabPanel,radioChip,chip,segment} from '../components/tabs-chips/render.mjs';
/* Immediate, local-only specimens. No search, save or API request. */
{
 const board=document.createElement('section');board.id='tabs-chips';board.className='board';board.dataset.component='tabs-chips';
 const radio=(id,label,name,checked=false)=>radioChip({id,label,name,checked});
 board.innerHTML='<div class="board-heading"><span>COMPONENTS / TABS & CHIPS</span><h1>탭·칩</h1><p>내용 전환과 보기 방식, 필터 선택을 구분합니다.</p></div>'+
 '<section class="tc-section" id="tabs-specimen"><div class="tc-heading"><h2>탭</h2><button data-field-prompt="tabs-specimen">AI 프롬프트</button></div><div class="tc-demo">'+tabs({id:'history',label:'마일리지 내역 예시',items:['전체','적립','사용']})+['모든 내역이 표시되는 영역입니다.','적립 내역만 표시되는 영역입니다.','사용 내역만 표시되는 영역입니다.'].map((text,i)=>tabPanel({id:'history',index:i,contentHTML:'<strong>'+text+'</strong>'})).join('')+'</div><p class="tc-note">터치 높이 48 · 좌우 여백 16 · 선택 표시선 2. 선택은 색과 하단 선으로 구분합니다. 탭을 선택하면 아래 내용을 전환합니다.</p><h3>상태 예시</h3>'+tabs({id:'tab-states',label:'정적 상태 비교',items:[{label:'선택',attributes:{'aria-disabled':'true'}},{label:'포커스',className:'is-focus',attributes:{'aria-disabled':'true'}},{label:'준비 중',disabled:true}]})+'<p class="tc-note">비활성 탭은 이동에서 제외합니다. 조회 중·오류·빈 결과는 탭 이름을 바꾸지 않고 연결된 콘텐츠 영역에서 안내하며, 재시도 후에도 현재 선택을 유지합니다.</p></section>'+
 '<section class="tc-section" id="segment-specimen"><div class="tc-heading"><h2>분할 선택</h2><button data-field-prompt="segment-specimen">AI 프롬프트</button></div><div class="tc-demo"><h3 id="segment-label">매장 보기 방식</h3>'+segment({name:'store-view',labelledBy:'segment-label',items:[{id:'segment-list',label:'목록'},{id:'segment-map',label:'지도'}]})+'<p id="segment-result" class="tc-status" role="status">선택한 보기: 목록</p></div><p class="tc-note">하나의 데이터에 대한 보기 방식·정렬 등 2~3개의 짧은 선택지에 사용합니다. 내부 여백 4 · 선택면 모서리 8 · 각 항목 터치 높이 48. 라디오 그룹으로 한 개만 선택하며 방향키로 전환합니다. 선택면의 짧은 그림자만 사용하고 움직이는 장식 효과는 넣지 않습니다. 항목명이 길어지면 축소하거나 두 줄로 만들지 말고 라디오 목록으로 전환합니다.</p></section>'+
 '<section class="tc-section" id="chips-specimen"><div class="tc-heading"><h2>칩</h2><button data-field-prompt="chips-specimen">AI 프롬프트</button></div><div class="tc-demo"><h3 id="single-chip-label">단일 선택</h3><div class="og-chip-group" role="radiogroup" aria-labelledby="single-chip-label">'+['전체','카페','식당'].map((x,i)=>radio('chip-single-'+i,x,'single-category',i===0)).join('')+'</div></div><div class="tc-demo"><h3 id="multi-chip-label">복수 선택</h3><div class="og-chip-group" id="multi-chips" role="group" aria-labelledby="multi-chip-label">'+['카페','식당','미용실','네일샵'].map(x=>chip({label:x,attributes:{'data-filter':x,'aria-describedby':'chip-status'}})).join('')+'</div><p id="chip-status" class="tc-status" role="status">0 / 3개 선택</p></div><div class="tc-demo"><h3>적용 필터 삭제</h3><div class="og-chip-group" id="removable-chips"></div><p id="remove-chip-status" class="tc-status" role="status">× 버튼으로 개별 필터를 지웁니다.</p><button id="chip-reset" type="button">필터 초기화</button></div><div class="tc-state-grid"><div><p>선택</p>'+chip({label:'✓ 선택됨',selected:true})+'</div><div><p>비활성</p>'+chip({label:'준비 중',disabled:true})+'</div><div><p>포커스</p>'+chip({label:'필터',className:'is-focus'})+'</div><div><p>기본</p>'+chip({label:'필터'})+'</div></div><p class="tc-note">터치 높이 48 · 좌우 여백 16 · 알약형 모서리. 선택 상태는 색과 체크 기호를 함께 사용합니다. 단일 선택은 하나만, 복수 선택은 여러 항목을 선택할 수 있습니다. 선택 한도에 도달해도 해제는 항상 가능하며 초과 선택 시 이유를 안내합니다. 삭제 버튼에는 ‘카페 필터 삭제’처럼 이름을 주고 삭제 후 다음 필터 또는 초기화 버튼으로 포커스를 옮깁니다. 긴 문구는 버튼 안에서 줄바꿈하지 않고 칩 자체를 다음 행으로 배치합니다.</p></section>'+
 '<h2>상태 적용 범위</h2><ul class="rules-list"><li>선택·미선택·마우스 오버·포커스·누름·비활성을 구분합니다. 의미 없는 로딩·성공 장식을 컨트롤에 반복하지 않습니다.</li><li>필터 조회 중에는 현재 선택을 유지하고 결과 영역에서 로딩을 보여줍니다. 실패 시 원인과 재시도를 제공하며 마지막 선택값을 잃지 않습니다.</li><li>확정 버튼이 있는 필터 시트는 임시 선택과 적용된 필터를 분리합니다.</li></ul>';
 document.querySelector('#world').append(board);const nav=document.createElement('button');nav.dataset.board='tabs-chips';nav.textContent='탭·칩';document.querySelector('aside nav').append(nav);document.querySelector('#board-picker').append(new Option('탭·칩','tabs-chips'));
}
